# SPDX-License-Identifier: AGPL-3.0-only
"""Metnos runtime — public stub.

This is the public skeleton of the Metnos runtime. The full agent
(ReAct planner, executor catalogue, vaglio sandbox, scheduler,
indices) lands in follow-up commits. For now the stub exposes:

- a working HTTP server on the configured port
- /agent/health (200) so the installer health probe passes
- /admin/onboard accepting the HMAC token generated by the installer
- a placeholder index page directing visitors at metnos.com

When the full runtime ships, the import surface stays the same;
consumers (skills, executors, the systemd unit) keep working.
"""

__version__ = "0.1.0-stub"
