# Copie residue post-ripristino (blob dedup): copia SORGENTE→DEST sul PC
# PowerShell:  Copy-Item 'SRC' 'DST'
Copy-Item 'C:\Users\rober\Downloads\patch_fixed_only (1).zip' 'C:\Users\rober\Downloads\patch_fixed_only (2).zip'
Copy-Item 'C:\Users\rober\Downloads\patch_fixed_only (11).zip' 'C:\Users\rober\Downloads\patch_fixed_only (12).zip'
Copy-Item 'C:\Users\rober\Downloads\patch_rich_layout_v2 (1).zip' 'C:\Users\rober\Downloads\patch_rich_layout_v2.zip'
Copy-Item 'C:\Users\rober\Downloads\patch_textual_ui (1).zip' 'C:\Users\rober\Downloads\patch_textual_ui.zip'
Copy-Item 'C:\Users\rober\Downloads\Report Febbraio 2026 - Roberto Brunialti (1).xlsx' 'C:\Users\rober\Downloads\Report Febbraio 2026 - Roberto Brunialti (2).xlsx'
Copy-Item 'C:\Users\rober\Downloads\Report Febbraio 2026 - Roberto Brunialti (1).xlsx' 'C:\Users\rober\Downloads\Report Febbraio 2026 - Roberto Brunialti (3).xlsx'
Copy-Item 'C:\Users\rober\Downloads\Report Febbraio 2026 - Roberto Brunialti (1).xlsx' 'C:\Users\rober\Downloads\Report Febbraio 2026 - Roberto Brunialti.xlsx'
Copy-Item 'C:\Users\rober\Downloads\SentimentWeb_fixed (1).zip' 'C:\Users\rober\Downloads\SentimentWeb_fixed.zip'
Copy-Item 'C:\Users\rober\Downloads\sentimentweb_fixed_full (1).zip' 'C:\Users\rober\Downloads\sentimentweb_fixed_full.zip'
Copy-Item 'C:\Users\rober\Downloads\sentimentweb_fixed_mailer_20251117 (1).zip' 'C:\Users\rober\Downloads\sentimentweb_fixed_mailer_20251117.zip'
Copy-Item 'C:\Users\rober\Downloads\sentimentweb_fixes (11).zip' 'C:\Users\rober\Downloads\sentimentweb_fixes.zip'
Copy-Item 'C:\Users\rober\Downloads\sentimentweb_fix_web_app (1).zip' 'C:\Users\rober\Downloads\sentimentweb_fix_web_app.zip'
Copy-Item 'C:\Users\rober\Downloads\sentiment_app_fixed (1).zip' 'C:\Users\rober\Downloads\sentiment_app_fixed (2).zip'
Copy-Item 'C:\Users\rober\Downloads\sentiment_app_fixed (1).zip' 'C:\Users\rober\Downloads\sentiment_app_fixed.zip'
Copy-Item 'C:\Users\rober\Downloads\sentiment_frontend_fix_v4 (1).zip' 'C:\Users\rober\Downloads\sentiment_frontend_fix_v4.zip'
Copy-Item 'C:\Users\rober\Downloads\sentiment_frontend_v5 (1).zip' 'C:\Users\rober\Downloads\sentiment_frontend_v5.zip'
Copy-Item 'C:\Users\rober\Downloads\serve (1).py' 'C:\Users\rober\Downloads\serve.py'
Copy-Item 'C:\Users\rober\Downloads\smtp_diag_patch (1).zip' 'C:\Users\rober\Downloads\smtp_diag_patch.zip'
Copy-Item 'C:\Users\rober\Downloads\smtp_fix_bundle (1).zip' 'C:\Users\rober\Downloads\smtp_fix_bundle.zip'
Copy-Item 'C:\Users\rober\Downloads\tenggen_card_double_sided (1).pdf' 'C:\Users\rober\Downloads\tenggen_card_double_sided.pdf'
Copy-Item 'C:\Users\rober\Downloads\ucg_mi_d (1).csv' 'C:\Users\rober\Downloads\ucg_mi_d (2).csv'
Copy-Item 'C:\Users\rober\Downloads\ucg_mi_d (1).csv' 'C:\Users\rober\Downloads\ucg_mi_d.csv'
Copy-Item 'C:\Users\rober\Downloads\VC_redist.x86 (1).exe' 'C:\Users\rober\Downloads\VC_redist.x86 (2).exe'
Copy-Item 'C:\Users\rober\Downloads\VC_redist.x86 (1).exe' 'C:\Users\rober\Downloads\VC_redist.x86 (3).exe'
Copy-Item 'C:\Users\rober\Downloads\VC_redist.x86 (1).exe' 'C:\Users\rober\Downloads\VC_redist.x86 (4).exe'
Copy-Item 'C:\Users\rober\Downloads\VC_redist.x86 (1).exe' 'C:\Users\rober\Downloads\VC_redist.x86.exe'
Copy-Item 'C:\Users\rober\Downloads\VisualStudioSetup (1).exe' 'C:\Users\rober\Downloads\VisualStudioSetup.exe'
Copy-Item 'C:\Users\rober\Downloads\watchlists (1).json' 'C:\Users\rober\Downloads\watchlists (2).json'
Copy-Item 'C:\Users\rober\Downloads\watchlists (1).json' 'C:\Users\rober\Downloads\watchlists (3).json'
Copy-Item 'C:\Users\rober\Downloads\watchlists (1).json' 'C:\Users\rober\Downloads\watchlists (4).json'
Copy-Item 'C:\Users\rober\Downloads\watchlists (1).json' 'C:\Users\rober\Downloads\watchlists (5).json'
Copy-Item 'C:\Users\rober\Downloads\watchlists (1).json' 'C:\Users\rober\Downloads\watchlists (6).json'
Copy-Item 'C:\Users\rober\Downloads\watchlists (1).json' 'C:\Users\rober\Downloads\watchlists.json'