#!/usr/bin/env python3
"""Test del daemon detection_translate_pending (offline, LLM mockato).

Verifica il meccanismo "aggiungi lingua -> auto-traduzione" senza GPU:
  - enqueue di una lingua nuova marca ogni concept pending;
  - il daemon traduce phrases/mapping via LLM (mock) e salva forme native;
  - i concept regex sono SALTATI (authoring manuale) e restano pending;
  - dopo il drenaggio, la copertura della lingua = tutto TRANNE i regex.
DB isolato in tmp (no pollution del detection.sqlite reale).
"""
import json
import sys
from pathlib import Path

_RUNTIME = (Path(__file__).resolve().parents[3] / "runtime")

import detection_lexicon as dl  # noqa: E402


def _fresh(tmp_path, monkeypatch):
    monkeypatch.setattr(dl, "DB_PATH", tmp_path / "detection.sqlite")
    monkeypatch.setattr(dl, "_conn", None)
    monkeypatch.setattr(dl, "_seeded", False)
    dl._cache.clear()
    dl._regex_cache.clear()
    monkeypatch.setenv("METNOS_DETECTION_AUDIT_DIR", str(tmp_path / "audit"))
    monkeypatch.setenv("METNOS_DETECTION_CAP_PER_FIRE", "100")
    dl.ensure_seeded()


def _install_mock_llm(monkeypatch):
    import llm_helpers

    def fake(prompt, sysp, tier=None, max_tokens=0, temperature=0.0):
        # Mock robusto: non dipende dal parsing del prompt (verifica il
        # daemon, non la regex del mock). Mapping -> mapping non vuoto valido.
        if "Source map (JSON)" in prompt:
            return json.dumps({"mapping": {"k": ["X_a", "X_b"]}}), {"model": "mock"}
        return json.dumps({"forms": ["X_a", "X_b"]}), {"model": "mock"}

    monkeypatch.setattr(llm_helpers, "call_llm", fake)


def _regex_concepts():
    out = set()
    for c in dl.registered_concepts():
        nat = dl._native(c, "en") or dl._native(c, "it")
        if nat and nat[0] == "regex":
            out.add(c)
    return out


def test_enqueue_marks_all_pending(tmp_path, monkeypatch):
    _fresh(tmp_path, monkeypatch)
    n = dl.enqueue_language("zz")
    assert n == len(dl.registered_concepts())
    assert len(dl.list_pending(limit=1000)) == n


def test_daemon_translates_phrases_and_mapping(tmp_path, monkeypatch):
    _fresh(tmp_path, monkeypatch)
    _install_mock_llm(monkeypatch)
    dl.enqueue_language("zz")
    from jobs.detection_translate_pending import task_detection_translate_pending
    res = task_detection_translate_pending()
    assert res["ok"]
    regex = _regex_concepts()
    non_regex = [c for c in dl.registered_concepts() if c not in regex]
    untranslated = [c for c in non_regex if not dl.has_native(c, "zz")]
    # tradotti = tutti i non-regex; saltati = regex
    assert res["metadata"]["translated"] == len(non_regex), \
        f"untranslated non-regex: {untranslated}; meta={res['metadata']}"
    assert res["metadata"]["skipped_regex"] == len(regex)


def test_coverage_after_translation_only_regex_missing(tmp_path, monkeypatch):
    _fresh(tmp_path, monkeypatch)
    _install_mock_llm(monkeypatch)
    dl.enqueue_language("zz")
    from jobs.detection_translate_pending import task_detection_translate_pending
    task_detection_translate_pending()
    cov = dl.verify_coverage("zz")
    assert set(cov["missing"]) == _regex_concepts()
    # un concept phrases/mapping ora ha forme native nella lingua nuova
    assert dl.has_native("notify.request", "zz")
    assert dl.has_native("notify.channel", "zz")


def test_regex_not_autogenerated(tmp_path, monkeypatch):
    """I regex restano pending (no pattern auto-generato fragile, §2.8)."""
    _fresh(tmp_path, monkeypatch)
    _install_mock_llm(monkeypatch)
    dl.enqueue_language("zz")
    from jobs.detection_translate_pending import task_detection_translate_pending
    task_detection_translate_pending()
    for c in _regex_concepts():
        assert not dl.has_native(c, "zz")
