#!/usr/bin/env python3
"""Test del daemon detection_translate_pending (offline, LLM mockato).

Verifica il meccanismo "aggiungi lingua -> auto-traduzione" senza GPU:
  - enqueue di una lingua nuova marca ogni concept pending;
  - il daemon traduce phrases/mapping via LLM (mock) e salva forme native;
  - i concept regex sono SALTATI (authoring manuale) e restano pending;
  - dopo il drenaggio, la copertura della lingua = tutto TRANNE i regex.
DB isolato in tmp (no pollution del detection.sqlite reale).
"""
import json
import sys
from pathlib import Path

_RUNTIME = (Path(__file__).resolve().parents[3] / "runtime")

import detection_lexicon as dl  # noqa: E402


def _fresh(tmp_path, monkeypatch):
    monkeypatch.setattr(dl, "DB_PATH", tmp_path / "detection.sqlite")
    monkeypatch.setattr(dl, "_conn", None)
    monkeypatch.setattr(dl, "_seeded", False)
    dl._cache.clear()
    dl._regex_cache.clear()
    monkeypatch.setenv("METNOS_DETECTION_AUDIT_DIR", str(tmp_path / "audit"))
    monkeypatch.setenv("METNOS_DETECTION_CAP_PER_FIRE", "100")
    dl.ensure_seeded()


def _install_mock_llm(monkeypatch):
    import llm_helpers

    def fake(prompt, sysp, tier=None, max_tokens=0, temperature=0.0):
        # Mock robusto: non dipende dal parsing del prompt (verifica il
        # daemon, non la regex del mock). Mapping -> mapping non vuoto valido.
        if "Source map (JSON)" in prompt:
            return json.dumps({"mapping": {"k": ["X_a", "X_b"]}}), {"model": "mock"}
        return json.dumps({"forms": ["X_a", "X_b"]}), {"model": "mock"}

    monkeypatch.setattr(llm_helpers, "call_llm", fake)


def _regex_concepts():
    out = set()
    for c in dl.registered_concepts():
        nat = dl._native(c, "en") or dl._native(c, "it")
        if nat and nat[0] == "regex":
            out.add(c)
    return out


def _non_auto_traducibili():
    """Concetti che il daemon NON deve tradurre da solo.

    Due categorie, per due ragioni diverse: i `regex`, perche' un pattern
    sbagliato e' peggio di un buco; e i concetti che governano un CONSENSO,
    perche' li' una forma inventata non produce un mancato riconoscimento ma
    un si' che l'utente non ha detto.
    """
    from detection_lexicon_seed import HUMAN_REVIEW_CONCEPTS
    return _regex_concepts() | set(HUMAN_REVIEW_CONCEPTS)


def test_enqueue_marks_all_pending(tmp_path, monkeypatch):
    _fresh(tmp_path, monkeypatch)
    n = dl.enqueue_language("zz")
    assert n == len(dl.registered_concepts())
    assert len(dl.list_pending(limit=1000)) == n


def test_daemon_translates_phrases_and_mapping(tmp_path, monkeypatch):
    _fresh(tmp_path, monkeypatch)
    _install_mock_llm(monkeypatch)
    dl.enqueue_language("zz")
    from jobs.detection_translate_pending import task_detection_translate_pending
    res = task_detection_translate_pending()
    assert res["ok"]
    saltati = _non_auto_traducibili()
    non_regex = [c for c in dl.registered_concepts() if c not in saltati]
    untranslated = [c for c in non_regex if not dl.has_native(c, "zz")]
    # tradotti = tutti gli auto-traducibili; trattenuti = regex + consenso
    assert res["metadata"]["translated"] == len(non_regex), \
        f"untranslated non-regex: {untranslated}; meta={res['metadata']}"
    # Le righe intraducibili sono escluse in SQL (17/8): non entrano piu' nella
    # finestra, quindi `skipped_*` — che conta cio' che il giro ha LETTO e
    # messo da parte — resta a zero, e il conto vive in `held_*`. Le due cose
    # restano distinte: una finestra piena di righe da tradurre e una finestra
    # piena di righe che nessun modello puo' toccare non sono lo stesso esito.
    from detection_lexicon_seed import HUMAN_REVIEW_CONCEPTS
    trattenuti = res["metadata"]["held_regex"] + res["metadata"]["held_consent"]
    assert trattenuti == len(saltati), res["metadata"]
    assert res["metadata"]["held_consent"] == len(HUMAN_REVIEW_CONCEPTS)
    assert res["metadata"]["skipped_regex"] == 0


def test_coverage_after_translation_only_regex_missing(tmp_path, monkeypatch):
    _fresh(tmp_path, monkeypatch)
    _install_mock_llm(monkeypatch)
    dl.enqueue_language("zz")
    from jobs.detection_translate_pending import task_detection_translate_pending
    task_detection_translate_pending()
    cov = dl.verify_coverage("zz")
    assert set(cov["missing"]) == _non_auto_traducibili()
    # un concept phrases/mapping ora ha forme native nella lingua nuova
    assert dl.has_native("notify.request", "zz")
    assert dl.has_native("notify.channel", "zz")


def test_regex_not_autogenerated(tmp_path, monkeypatch):
    """I regex restano pending (no pattern auto-generato fragile, §2.8)."""
    _fresh(tmp_path, monkeypatch)
    _install_mock_llm(monkeypatch)
    dl.enqueue_language("zz")
    from jobs.detection_translate_pending import task_detection_translate_pending
    task_detection_translate_pending()
    for c in _regex_concepts():
        assert not dl.has_native(c, "zz")


def test_i_concetti_di_consenso_non_si_traducono_da_soli(monkeypatch):
    """`confirm.*` decidono se un consenso e' stato dato.

    Una forma inventata da un modello e mai riletta da nessuno non produce qui
    un mancato riconoscimento: produce un si' che l'utente non ha detto. Il
    daemon li salta e li lascia a una persona. Nel frattempo l'unione con it/en
    tiene utilizzabile la lingua nuova, perche' «ok», «yes», «no» e «stop»
    sono prestiti che si scrivono quasi ovunque.

    Prima del 16/8/2026 il caso non si poneva: erano `kind="regex"` e il
    daemon saltava tutti i regex. Passandoli a `phrases` sono entrati nel
    perimetro della traduzione automatica, e questo gate e' cio' che li
    riporta fuori.
    """
    from jobs import detection_translate_pending as _job

    chiamate = []

    def _mai(*a, **k):
        chiamate.append(a)
        return None, {}

    monkeypatch.setattr(_job, "_llm_localize", _mai)

    riga = {"concept": "confirm.yes", "target_lang": "de", "kind": "phrases",
            "source_lang": "it", "source_payload": '["si"]'}

    def _finto_list_pending(limit=0, exclude_concepts=(), exclude_kinds=()):
        """Riproduce l'esclusione in SQL: chi filtra a monte non vede la riga.

        La riga resta visibile alla chiamata SENZA esclusioni, che e' quella
        con cui il job conta i trattenuti."""
        if riga["concept"] in exclude_concepts or riga["kind"] in exclude_kinds:
            return []
        return [dict(riga)]

    monkeypatch.setattr(_job._dl, "list_pending", _finto_list_pending)
    esito = _job.task_detection_translate_pending()
    assert chiamate == [], "il modello NON deve essere interpellato"
    assert esito["metadata"]["held_consent"] >= 1, esito["metadata"]


def test_il_backstop_nel_ciclo_regge_se_l_esclusione_non_arriva(monkeypatch):
    """Doppia difesa: se la riga di consenso entra comunque nella finestra —
    una `list_pending` che ignora le esclusioni, come faceva la vecchia — il
    controllo dentro il ciclo la ferma lo stesso. L'esclusione in SQL e' per
    non sprecare la finestra, non e' cio' che protegge il consenso."""
    from jobs import detection_translate_pending as _job

    chiamate = []
    monkeypatch.setattr(_job, "_llm_localize",
                        lambda *a, **k: (chiamate.append(a), (None, {}))[1])
    monkeypatch.setattr(
        _job._dl, "list_pending",
        lambda limit=0, exclude_concepts=(), exclude_kinds=(): [
            {"concept": "confirm.no", "target_lang": "de", "kind": "phrases",
             "source_lang": "it", "source_payload": '["no"]'},
        ])
    esito = _job.task_detection_translate_pending()
    assert chiamate == [], "il modello NON deve essere interpellato"
    assert esito["metadata"]["skipped_regex"] >= 1, esito["metadata"]
