"""queries_500_builder.py — 500 query SOLO su domini realmente coperti.

13 domini catalog (73 executor):
- files, dirs (fs locale)
- messages (mail IMAP)
- events (calendar)
- persons, contacts
- images (foto + face indices)
- urls (web search + read_urls_html/pdf)
- files_doc, files_spreadsheet, files_csv, files_ocr (gdocs/sheets)
- tasks scheduler (builtin)
- places (geo)
- processes (sys info generic)
- packages (apt/pip)
- credentials

NO smart home, NO IoT, NO network low-level, NO math basic.
Github = read_urls_html su github.com/X URLs.
Google Workspace = create_files_doc / write_files_spreadsheet / read_files_doc.

Annotations strette (no catch-all relaxation).
"""
from __future__ import annotations

TEST_QUERIES_500: list[dict] = []


def Q(query: str, expected: list[str], accepted: set[str]):
    TEST_QUERIES_500.append({
        "query": query,
        "expected_path": expected,
        "accepted_first": accepted,
    })


# === FILES (50) ===
Q("file nella cartella /tmp", ["find_files"], {"find_files", "list_dirs"})
Q("conta file in /tmp", ["find_files", "compute_entries"], {"find_files"})
Q("file più pesanti in /var", ["find_files", "sort_entries"], {"find_files"})
Q("file *.txt in Documenti", ["find_files"], {"find_files"})
Q("file modificati ieri in home", ["find_files"], {"find_files"})
Q("file più vecchi di 30 giorni in /tmp", ["find_files"], {"find_files"})
Q("file > 100MB in /var/log", ["find_files"], {"find_files"})
Q("ultimo backup creato in /var/backups", ["find_files", "sort_entries"], {"find_files"})
Q("conta pdf in /home/user/docs", ["find_files", "compute_entries"], {"find_files"})
Q("file con estensione .log in /var", ["find_files"], {"find_files"})
Q("dimensione del file /home/user/grosso.bin", ["get_files"], {"get_files", "get_file_dates"})
Q("permessi del file /etc/hosts", ["get_files"], {"get_files"})
Q("data ultima modifica di /tmp/x.log", ["get_file_dates"], {"get_file_dates", "get_files"})
Q("controlla se /tmp/x.lock esiste", ["find_files"], {"find_files", "get_files"})
Q("file più recente in Downloads", ["find_files", "sort_entries"], {"find_files"})
Q("sposta /tmp/a.txt in /home/roberto", ["move_files"], {"move_files"})
Q("copia jpg da Foto a Backup", ["find_files", "move_files"], {"find_files"})
Q("elimina file *.bak in /tmp", ["find_files", "delete_files"], {"find_files", "delete_files"})
Q("cancella /tmp/foo.txt", ["delete_files"], {"delete_files"})
Q("rinomina /tmp/test.py in test_v2.py", ["move_files"], {"move_files"})
Q("scrivi /tmp/note.txt con 'hello world'", ["write_files"], {"write_files"})
Q("crea file vuoto /tmp/lock", ["write_files"], {"write_files"})
Q("converti /home/x.png in jpg", ["change_files_format"], {"change_files_format"})
Q("checksum sha256 di /tmp/a.iso", ["compute_signatures"], {"compute_signatures"})
Q("verifica firma di /tmp/release.tar.gz", ["compute_signatures"], {"compute_signatures"})
Q("size totale cartella /home/roberto", ["find_files", "compute_entries"], {"find_files"})
Q("file zero byte in /tmp", ["find_files"], {"find_files"})
Q("file con root come owner in /etc", ["find_files"], {"find_files"})
Q("ultimi 5 file creati", ["find_files", "sort_entries"], {"find_files"})
Q("righe di codice in /opt/metnos/runtime", ["compute_files_loc"], {"compute_files_loc", "find_files"})
Q("conta linee python in /tmp", ["find_files", "compute_files_loc"], {"find_files", "compute_files_loc"})
Q("file pdf in Documenti modificati ultima settimana", ["find_files"], {"find_files"})
Q("ordina file in Downloads per dimensione", ["find_files", "sort_entries"], {"find_files"})
Q("script bash in /opt/metnos/install", ["find_files"], {"find_files"})
Q("file di configurazione yml in /etc", ["find_files"], {"find_files"})
Q("file con timestamp più antico in /var", ["find_files", "sort_entries"], {"find_files"})
Q("file duplicati per hash in /Backup", ["find_files", "compute_signatures"], {"find_files"})
Q("dimensione media file in /opt/metnos", ["find_files", "compute_entries"], {"find_files"})
Q("totale spazio occupato da /home/user/Documenti", ["find_files", "compute_entries"], {"find_files"})
Q("share /home/user/x.pdf con marco@x.it", ["share_files"], {"share_files"})
Q("read /tmp/manuale.pdf", ["read_files"], {"read_files"})
Q("contenuto di /etc/hosts", ["read_files"], {"read_files"})
Q("OCR su /tmp/scansione.png", ["read_files_ocr"], {"read_files_ocr", "read_files"})
Q("estrai testo da /tmp/contratto.pdf", ["read_files"], {"read_files"})
Q("filtra righe con TODO da /tmp/log.txt", ["read_files", "filter_texts_lines"], {"read_files", "filter_texts_lines"})
Q("cerca pattern ERROR in /var/log/syslog", ["read_files", "filter_texts_lines"], {"read_files", "filter_texts_lines"})
Q("file di log con errori di stamani", ["find_files", "read_files"], {"find_files"})
Q("ultimo 100 righe di /var/log/syslog", ["read_files"], {"read_files"})
Q("conta linee di /tmp/data.csv", ["compute_files_loc"], {"compute_files_loc", "read_files"})
Q("dimensione cartella Documenti più grande di Downloads", ["find_files", "compare_entries"], {"find_files", "find_dirs"})

# === DIRS (35) ===
Q("cartelle in /home/roberto", ["list_dirs"], {"list_dirs", "find_dirs"})
Q("conta cartelle in /opt", ["find_dirs", "compute_entries"], {"find_dirs", "list_dirs"})
Q("cartella più pesante in /var", ["find_dirs", "sort_entries"], {"find_dirs"})
Q("cartelle vuote in /tmp", ["find_dirs"], {"find_dirs"})
Q("cartelle modificate oggi", ["find_dirs"], {"find_dirs"})
Q("subdir di /home/user/Progetti", ["list_dirs"], {"list_dirs", "find_dirs"})
Q("crea cartella /tmp/newdir", ["create_dirs"], {"create_dirs"})
Q("crea albero /tmp/proj/src/lib", ["create_dirs"], {"create_dirs"})
Q("elimina cartella /tmp/oldproject", ["delete_dirs"], {"delete_dirs"})
Q("alberatura completa /etc", ["list_dirs"], {"list_dirs", "find_dirs"})
Q("dimensione cartella /usr/share", ["find_files", "compute_entries"], {"find_files", "find_dirs"})
Q("cartelle con più di 1000 file", ["find_dirs"], {"find_dirs"})
Q("cartelle nascoste in home", ["find_dirs"], {"find_dirs"})
Q("dir profonde più di 5 livelli", ["find_dirs"], {"find_dirs"})
Q("backup dir in /var/backups", ["list_dirs"], {"list_dirs", "find_dirs"})
Q("home utenti su questa macchina", ["list_dirs"], {"list_dirs", "find_dirs"})
Q("svuota cartella /tmp/cache", ["find_files", "delete_files"], {"find_files"})
Q("compara /home/a e /home/b", ["find_files", "compare_entries"], {"find_dirs", "find_files"})
Q("cartelle senza accesso lettura", ["find_dirs"], {"find_dirs"})
Q("ultima cartella creata in /home", ["find_dirs", "sort_entries"], {"find_dirs"})
Q("conta sottocartelle ricorsivo in /etc", ["find_dirs", "compute_entries"], {"find_dirs", "list_dirs"})
Q("dir con .git dentro", ["find_dirs"], {"find_dirs", "find_files"})
Q("project root metnos", ["find_dirs"], {"find_dirs", "list_dirs"})
Q("cartelle con file modificati ultima settimana", ["find_dirs", "find_files"], {"find_dirs", "find_files"})
Q("home directory dell'utente roberto", ["list_dirs"], {"list_dirs", "find_dirs"})
Q("cartelle in /opt che contengono executor", ["find_dirs"], {"find_dirs"})
Q("cartelle progetti python in home", ["find_dirs"], {"find_dirs"})
Q("totale file in tutte le cartelle di /home", ["find_files", "compute_entries"], {"find_files", "find_dirs"})
Q("cartelle vuote da cancellare in /tmp", ["find_dirs", "delete_dirs"], {"find_dirs"})
Q("sposta /tmp/work in /home/roberto", ["move_files"], {"move_files"})
Q("rinomina /home/old in /home/new", ["move_files"], {"move_files"})
Q("cartella più recente in Downloads", ["find_dirs", "sort_entries"], {"find_dirs"})
Q("classifica cartelle per linguaggio progetto", ["find_dirs", "classify_entries"], {"find_dirs"})
Q("raggruppa file per estensione in /tmp", ["find_files", "group_entries"], {"find_files"})
Q("ordina cartelle per data modifica", ["find_dirs", "sort_entries"], {"find_dirs", "list_dirs"})

# === MESSAGES / MAIL (45) ===
Q("mail in inbox", ["read_messages"], {"read_messages"})
Q("mail oggi", ["read_messages"], {"read_messages"})
Q("mail da carlo@x.it", ["read_messages"], {"read_messages"})
Q("mail non lette", ["read_messages"], {"read_messages"})
Q("mail con allegati", ["read_messages"], {"read_messages"})
Q("mail con oggetto fattura", ["read_messages"], {"read_messages"})
Q("ultima mail ricevuta", ["read_messages"], {"read_messages"})
Q("mail della settimana scorsa", ["read_messages"], {"read_messages"})
Q("invia 'ciao' a marco@x.it", ["send_messages"], {"send_messages"})
Q("rispondi a Marco ok", ["read_messages", "reply_messages"], {"read_messages", "reply_messages"})
Q("inoltra ultima mail a paolo@x.it", ["read_messages", "send_messages"], {"read_messages"})
Q("archivia mail vecchie 6 mesi", ["read_messages", "move_messages"], {"read_messages"})
Q("cestina mail spam", ["read_messages", "move_messages"], {"read_messages"})
Q("sposta mail di Mario in Lavoro", ["read_messages", "move_messages"], {"read_messages"})
Q("conta mail di Lucia", ["read_messages", "compute_entries"], {"read_messages"})
Q("mail con dimensione > 5MB", ["read_messages"], {"read_messages"})
Q("raggruppa mail per mittente", ["read_messages", "group_entries"], {"read_messages"})
Q("classifica mail importanti", ["read_messages", "classify_entries"], {"read_messages"})
Q("ultime 20 mail in posta arrivata", ["read_messages"], {"read_messages"})
Q("mail di stamattina", ["read_messages"], {"read_messages"})
Q("mail non lette del lavoro", ["read_messages"], {"read_messages"})
Q("mail con risposta richiesta", ["read_messages", "classify_entries"], {"read_messages"})
Q("estrai allegati ultima mail", ["read_messages"], {"read_messages"})
Q("sintesi mail di oggi", ["read_messages", "describe_entries"], {"read_messages"})
Q("mail con link a github.com", ["read_messages"], {"read_messages"})
Q("manda a Roberto la lista appuntamenti", ["read_events", "send_messages"], {"read_events"})
Q("riferisci a Paolo le mail nuove", ["read_messages", "send_messages"], {"read_messages"})
Q("svuota cestino mail", ["read_messages", "delete_files"], {"read_messages"})
Q("ordina mail per data", ["read_messages", "sort_entries"], {"read_messages"})
Q("rispondi a tutti i pending", ["read_messages", "reply_messages"], {"read_messages", "reply_messages"})
Q("mail di carlo poi crea evento riunione", ["read_messages", "create_events"], {"read_messages"})
Q("conta mail per mese", ["read_messages", "group_entries"], {"read_messages"})
Q("salva mail di oggi in /tmp/dump.json", ["read_messages", "write_files"], {"read_messages"})
Q("manda mail riassuntiva alle ore 20", ["create_events", "send_messages"], {"create_events", "read_messages"})
Q("imposta flag importante su mail di Lucia", ["read_messages", "set_messages"], {"read_messages", "set_messages"})
Q("contrassegna come letta tutte le mail di oggi", ["read_messages", "set_messages"], {"read_messages"})
Q("mail con sentiment negativo", ["read_messages", "classify_entries"], {"read_messages"})
Q("trova mail simili a 'fattura 2024'", ["read_messages"], {"read_messages"})
Q("genera pdf con mail importanti", ["read_messages", "write_files_doc"], {"read_messages"})
Q("ultime 5 mail importanti come pdf in /tmp/mail.pdf", ["read_messages", "write_files_doc"], {"read_messages"})
Q("estrai mail con allegato pdf in /tmp/all", ["read_messages", "write_files"], {"read_messages"})
Q("dimensione totale inbox", ["read_messages", "compute_entries"], {"read_messages"})
Q("mail non lette del cliente Alpha", ["read_messages"], {"read_messages"})
Q("ultima mail di banca importante", ["read_messages"], {"read_messages"})
Q("mail senza risposta da 7 giorni", ["read_messages"], {"read_messages"})

# === EVENTS (30) ===
Q("appuntamenti oggi", ["read_events"], {"read_events"})
Q("eventi domani", ["read_events"], {"read_events"})
Q("agenda settimana", ["read_events"], {"read_events"})
Q("riunioni martedi", ["read_events"], {"read_events"})
Q("evento più imminente", ["read_events", "sort_entries"], {"read_events"})
Q("slot libero pomeriggio", ["find_events_empty"], {"find_events_empty"})
Q("tempo libero domani mattina", ["find_events_empty"], {"find_events_empty"})
Q("crea evento dentista lunedi alle 10", ["create_events"], {"create_events"})
Q("nuovo appuntamento riunione martedi 15", ["create_events"], {"create_events"})
Q("cancella evento di ieri", ["read_events", "delete_events"], {"read_events", "delete_events"})
Q("eventi ricorrenti", ["read_events"], {"read_events"})
Q("compleanni del mese", ["read_events"], {"read_events"})
Q("conta eventi settimana", ["read_events", "compute_entries"], {"read_events"})
Q("primo evento del giorno", ["read_events", "sort_entries"], {"read_events"})
Q("eventi con luogo a Roma", ["read_events"], {"read_events"})
Q("evento più lungo della settimana", ["read_events", "sort_entries"], {"read_events"})
Q("eventi cancellati di recente", ["read_events"], {"read_events"})
Q("disponibilità venerdì pomeriggio", ["find_events_empty"], {"find_events_empty"})
Q("evento dentista trovalo", ["read_events"], {"read_events"})
Q("riassunto giornata", ["read_events", "describe_entries"], {"read_events"})
Q("appuntamenti del weekend", ["read_events"], {"read_events"})
Q("cosa ho lunedi", ["read_events"], {"read_events"})
Q("elenca eventi del mese", ["read_events"], {"read_events"})
Q("ho qualcosa stasera", ["read_events"], {"read_events", "find_events_empty"})
Q("crea promemoria comprare pane domani 18", ["create_events"], {"create_events", "create_tasks"})
Q("cancella appuntamento riunione di domani", ["read_events", "delete_events"], {"read_events", "delete_events"})
Q("prossimo compleanno tra contatti", ["read_events"], {"read_events", "read_contacts"})
Q("tutti gli eventi di oggi raggruppati per luogo", ["read_events", "group_entries"], {"read_events"})
Q("eventi sovrapposti questo mese", ["read_events", "compare_entries"], {"read_events"})
Q("ordina eventi per durata", ["read_events", "sort_entries"], {"read_events"})

# === PERSONS / CONTACTS (25) ===
Q("chi sono io", ["read_persons"], {"read_persons", "get_persons"})
Q("dimmi tutto su Marco", ["read_persons"], {"read_persons", "get_persons"})
Q("scheda di Lucia", ["read_persons"], {"read_persons", "get_persons"})
Q("contatti famiglia", ["read_persons"], {"read_persons", "read_contacts"})
Q("ospiti in casa", ["read_persons"], {"read_persons"})
Q("guest abilitati", ["read_persons"], {"read_persons"})
Q("telefono di Lucia", ["read_persons"], {"read_persons", "read_contacts"})
Q("email di Paolo", ["read_persons"], {"read_persons", "read_contacts"})
Q("contatti di lavoro", ["read_persons"], {"read_persons", "read_contacts"})
Q("età di Lucia", ["read_persons"], {"read_persons", "get_persons"})
Q("dove abita Lucia", ["read_persons"], {"read_persons", "get_persons"})
Q("conta persone in rubrica", ["read_persons", "compute_entries"], {"read_persons", "read_contacts"})
Q("ultime persone aggiunte", ["read_persons", "sort_entries"], {"read_persons", "read_contacts"})
Q("foto di Mario", ["find_persons_indices"], {"find_persons_indices", "find_images_indices"})
Q("riconosci la persona in /tmp/foto.jpg", ["find_persons_indices"], {"find_persons_indices"})
Q("identifica volti in /home/Foto", ["find_persons_indices"], {"find_persons_indices"})
Q("ultime foto di Lucia", ["find_persons_indices", "sort_entries"], {"find_persons_indices"})
Q("conta foto di Marco", ["find_persons_indices", "compute_entries"], {"find_persons_indices"})
Q("cancella scheda persona Pietro", ["delete_persons"], {"delete_persons"})
Q("aggiorna dati di Marco", ["set_persons"], {"set_persons"})
Q("imposta nickname di Lucia", ["set_persons"], {"set_persons"})
Q("contatti senza email", ["read_persons"], {"read_persons", "read_contacts"})
Q("contatti senza foto", ["read_persons"], {"read_persons", "read_contacts"})
Q("ultimi contatti sentiti via mail", ["read_messages", "group_entries"], {"read_messages"})
Q("manda email a tutti i contatti family", ["read_persons", "send_messages"], {"read_persons", "read_contacts"})

# === IMAGES (25) ===
Q("foto al mare 2024", ["find_images_indices"], {"find_images_indices"})
Q("foto montagna estate", ["find_images_indices"], {"find_images_indices"})
Q("foto con la famiglia", ["find_persons_indices"], {"find_persons_indices", "find_images_indices"})
Q("scatti notturni recenti", ["find_images_indices"], {"find_images_indices"})
Q("foto sfocate da eliminare", ["find_images_indices"], {"find_images_indices"})
Q("indicizza nuove foto in /home/Foto", ["create_images_indices"], {"create_images_indices"})
Q("aggiorna indice foto", ["create_images_indices"], {"create_images_indices"})
Q("conta foto del 2024", ["find_images_indices", "compute_entries"], {"find_images_indices"})
Q("foto piu recente", ["find_images_indices", "sort_entries"], {"find_images_indices"})
Q("foto duplicate", ["find_images_indices"], {"find_images_indices"})
Q("ridimensiona /home/foto.jpg a 800x600", ["change_files_format"], {"change_files_format"})
Q("converti png in jpg in /Foto", ["find_files", "change_files_format"], {"find_files", "change_files_format"})
Q("estrai EXIF da /home/foto.jpg", ["get_files"], {"get_files", "get_file_dates"})
Q("foto scattate ad amsterdam", ["find_images_indices"], {"find_images_indices"})
Q("foto con volto sconosciuto", ["find_persons_indices"], {"find_persons_indices"})
Q("cancella indice foto vecchio", ["delete_images_indices"], {"delete_images_indices"})
Q("rebuild indice foto", ["delete_images_indices", "create_images_indices"], {"delete_images_indices", "create_images_indices"})
Q("ordina foto per data scatto", ["find_images_indices", "sort_entries"], {"find_images_indices"})
Q("raggruppa foto per luogo", ["find_images_indices", "group_entries"], {"find_images_indices"})
Q("classifica foto per persona", ["find_images_indices", "classify_entries"], {"find_images_indices", "find_persons_indices"})
Q("trova foto simili a /tmp/x.jpg", ["find_images_indices"], {"find_images_indices"})
Q("cerca foto sul web simili a /home/me.jpg", ["find_images_web"], {"find_images_web"})
Q("statistiche foto del 2024 per mese", ["find_images_indices", "group_entries"], {"find_images_indices"})
Q("dimensione media foto in /Foto", ["find_images_indices", "compute_entries"], {"find_images_indices", "find_files"})
Q("indicizza foto e poi mostra riassunto", ["create_images_indices", "describe_entries"], {"create_images_indices"})

# === URLS / WEB (40) — incluso github via read_urls_html ===
Q("cerca su google docker tutorial", ["find_urls"], {"find_urls"})
Q("notizie italia oggi", ["find_urls"], {"find_urls"})
Q("meteo milano", ["find_urls"], {"find_urls"})
Q("traduzione 'cane' in inglese", ["find_urls"], {"find_urls"})
Q("Wikipedia su Marco Polo", ["find_urls"], {"find_urls"})
Q("apri contenuto di https://example.com", ["read_urls_html"], {"read_urls_html"})
Q("scarica https://x.com/file.pdf", ["get_urls"], {"get_urls", "read_urls_pdf"})
Q("contenuto di https://www.repubblica.it", ["read_urls_html"], {"read_urls_html"})
Q("estrai pdf https://x.com/manuale.pdf", ["read_urls_pdf"], {"read_urls_pdf"})
Q("salva la pagina https://x.com/news in /tmp/news.html", ["read_urls_html", "write_files"], {"read_urls_html"})
Q("RSS feed phoronix", ["find_urls"], {"find_urls"})
Q("github stars di repo metnos", ["read_urls_html"], {"read_urls_html"})
Q("issue aperti su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("ultimo commit su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("pull request aperti su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("releases di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("contributors top di https://github.com/x/metnos", ["read_urls_html", "sort_entries"], {"read_urls_html"})
Q("README di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("file LICENSE in https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("issue chiusi ultima settimana su github metnos", ["read_urls_html"], {"read_urls_html"})
Q("cerca su web bug python asyncio", ["find_urls"], {"find_urls"})
Q("docs ufficiali python pathlib", ["find_urls"], {"find_urls"})
Q("amazon prezzo iphone 17", ["find_urls"], {"find_urls"})
Q("recensioni hotel a Roma", ["find_urls"], {"find_urls"})
Q("video youtube tutorial git", ["find_urls"], {"find_urls"})
Q("PDF su machine learning nel sito X", ["find_urls"], {"find_urls", "read_urls_pdf"})
Q("status code di https://x.com", ["read_urls_html"], {"read_urls_html"})
Q("scarica primo risultato cerca python tutorial", ["find_urls", "get_urls"], {"find_urls"})
Q("apri https://news.ycombinator.com", ["read_urls_html"], {"read_urls_html"})
Q("ultimo post su https://blog.x.com", ["read_urls_html"], {"read_urls_html"})
Q("estrai tutti i link da https://x.com/news", ["read_urls_html"], {"read_urls_html"})
Q("salva contenuto di https://x.com come file txt", ["read_urls_html", "write_files"], {"read_urls_html"})
Q("scarica documentazione pdf da https://x.com/manual.pdf", ["get_urls"], {"get_urls", "read_urls_pdf"})
Q("conteggio risultati google su 'metnos AI'", ["find_urls", "compute_entries"], {"find_urls"})
Q("apri release notes ultima versione di https://github.com/x/y", ["read_urls_html"], {"read_urls_html"})
Q("traccia pacco con tracking https://corriere.it/X", ["read_urls_html"], {"read_urls_html"})
Q("apri il foglio https://docs.google.com/spreadsheet/X", ["read_urls_html"], {"read_urls_html", "read_files_spreadsheet"})
Q("Wikipedia voce su Roma", ["find_urls", "read_urls_html"], {"find_urls", "read_urls_html"})
Q("estrai contenuto da https://stackoverflow.com/q/123", ["read_urls_html"], {"read_urls_html"})
Q("cerca su huggingface modelli LLM open", ["find_urls"], {"find_urls"})

# === FILES_DOC / FILES_SPREADSHEET / FILES_CSV / FILES_XLSX (35) ===
Q("apri ultimo documento", ["find_files", "read_files_doc"], {"find_files"})
Q("apri /home/user/budget.xlsx", ["read_files_spreadsheet"], {"read_files_spreadsheet", "read_files_xlsx"})
Q("dati da /tmp/data.csv", ["read_files_csv"], {"read_files_csv"})
Q("crea nuovo documento con titolo 'piano lavoro'", ["create_files_doc"], {"create_files_doc"})
Q("crea foglio calcolo /tmp/spese.xlsx", ["create_files_spreadsheet"], {"create_files_spreadsheet"})
Q("aggiungi riga al foglio spese in /home/spese.xlsx", ["read_files_spreadsheet", "write_files_spreadsheet"], {"read_files_spreadsheet"})
Q("scrivi /tmp/note.docx con 'memo'", ["write_files_doc"], {"write_files_doc"})
Q("scrivi /tmp/data.xlsx con dati riepilogo", ["write_files_spreadsheet"], {"write_files_spreadsheet"})
Q("converte /tmp/report.pdf in md", ["change_files_format"], {"change_files_format"})
Q("converte /tmp/a.docx in pdf", ["change_files_format"], {"change_files_format"})
Q("foglio fatturazione mese scorso in /home/Fatture", ["find_files"], {"find_files", "read_files_spreadsheet"})
Q("estrai dati tabellari da /tmp/report.xlsx", ["read_files_spreadsheet"], {"read_files_spreadsheet"})
Q("apri foglio budget 2026 in /home/Documenti", ["find_files", "read_files_spreadsheet"], {"find_files"})
Q("totale somma colonna A in /tmp/dati.xlsx", ["read_files_spreadsheet", "compute_entries"], {"read_files_spreadsheet"})
Q("apri documenti modificati ieri in /home/Docs", ["find_files", "read_files_doc"], {"find_files"})
Q("nuovo documento dal template invito", ["create_files_doc"], {"create_files_doc"})
Q("salva mail importanti come pdf in /tmp/mail.pdf", ["read_messages", "write_files_doc"], {"read_messages"})
Q("riassumi /tmp/manuale.pdf in 5 punti", ["read_files", "describe_entries"], {"read_files"})
Q("traduci /tmp/articolo.docx in inglese", ["read_files_doc"], {"read_files_doc", "read_files"})
Q("estrai email dai pdf in /tmp", ["find_files", "read_files"], {"find_files"})
Q("scrivi documento con elenco appuntamenti settimana", ["read_events", "write_files_doc"], {"read_events"})
Q("genera pdf con eventi della settimana", ["read_events", "write_files_doc"], {"read_events"})
Q("scrivi spreadsheet con statistiche mail mensili", ["read_messages", "write_files_spreadsheet"], {"read_messages"})
Q("conteggio righe in /tmp/data.csv", ["read_files_csv", "compute_entries"], {"read_files_csv"})
Q("apri primo foglio in /tmp/multi.xlsx", ["read_files_xlsx"], {"read_files_xlsx", "read_files_spreadsheet"})
Q("ordina /tmp/dati.csv per colonna data", ["read_files_csv", "sort_entries"], {"read_files_csv"})
Q("filtra righe /tmp/data.csv dove status=ok", ["read_files_csv", "filter_entries"], {"read_files_csv"})
Q("ultimo documento modificato in /home/Docs", ["find_files", "sort_entries"], {"find_files"})
Q("documenti senza titolo in /home/Docs", ["find_files"], {"find_files"})
Q("documenti condivisi con me", ["read_files"], {"read_files", "find_files"})
Q("estrai contenuto da /tmp/scansione.pdf con OCR", ["read_files_ocr"], {"read_files_ocr"})
Q("estrai testo da /tmp/scan.png con OCR", ["read_files_ocr"], {"read_files_ocr"})
Q("OCR su tutte le immagini in /tmp/scans", ["find_files", "read_files_ocr"], {"find_files"})
Q("riassumi documenti pdf in /home/Docs", ["find_files", "read_files", "describe_entries"], {"find_files"})
Q("salva risultato analisi in /tmp/output.xlsx", ["write_files_spreadsheet"], {"write_files_spreadsheet"})

# === PLACES / LOCATION (20) ===
Q("dove sono ora", ["get_location"], {"get_location", "get_places"})
Q("posizione attuale", ["get_location"], {"get_location", "get_places"})
Q("bar più vicino", ["find_places"], {"find_places"})
Q("supermercato aperto ora", ["find_places"], {"find_places"})
Q("indirizzo di casa", ["read_persons"], {"read_persons", "get_location"})
Q("posti visitati ieri", ["get_places"], {"get_places"})
Q("ristorante italiano vicino", ["find_places"], {"find_places"})
Q("farmacia di notte", ["find_places"], {"find_places"})
Q("hotel a Torino", ["find_places"], {"find_places"})
Q("come arrivare al duomo", ["find_places"], {"find_places", "find_urls"})
Q("parcheggi liberi vicino", ["find_places"], {"find_places"})
Q("stazioni treno milano", ["find_places"], {"find_places"})
Q("mappa quartiere lavoro", ["find_places"], {"find_places"})
Q("posto della cena di ieri", ["read_events"], {"read_events", "get_places"})
Q("luoghi più frequenti questo mese", ["get_places", "sort_entries"], {"get_places"})
Q("distanza dalla farmacia più vicina", ["find_places", "sort_entries"], {"find_places"})
Q("ricerca posti vicini a 'museo'", ["find_places"], {"find_places"})
Q("posti che ho visitato a Roma", ["get_places"], {"get_places"})
Q("foto scattate vicino a coordinate gps", ["find_images_indices"], {"find_images_indices"})
Q("eventi futuri vicino a casa", ["read_events"], {"read_events", "find_places"})

# === SYSTEM / PROCESSES / PACKAGES (20) ===
Q("processi attivi", ["get_processes"], {"get_processes"})
Q("top 5 processi per cpu", ["get_processes", "sort_entries"], {"get_processes"})
Q("processi zombie", ["get_processes"], {"get_processes"})
Q("metnos-http è attivo", ["get_processes"], {"get_processes"})
Q("uptime macchina", ["get_processes"], {"get_processes", "get_now"})
Q("ffmpeg installato", ["find_packages"], {"find_packages"})
Q("versione python installata", ["find_packages"], {"find_packages"})
Q("pacchetti installati", ["find_packages"], {"find_packages"})
Q("verifica se docker installato", ["find_packages"], {"find_packages"})
Q("dipendenze python progetto Alpha", ["read_files"], {"read_files", "find_files", "find_packages"})
Q("processi in errore", ["get_processes"], {"get_processes"})
Q("connessioni di rete aperte", ["get_processes"], {"get_processes"})
Q("classifica processi per memoria", ["get_processes", "classify_entries"], {"get_processes"})
Q("raggruppa processi per utente", ["get_processes", "group_entries"], {"get_processes"})
Q("conta processi attivi", ["get_processes", "compute_entries"], {"get_processes"})
Q("processo metnos-http ha più di 1GB di ram", ["get_processes"], {"get_processes"})
Q("ultimo restart di metnos-http", ["get_processes"], {"get_processes"})
Q("trova pacchetto da nome 'sqlite'", ["find_packages"], {"find_packages"})
Q("pacchetti obsoleti", ["find_packages"], {"find_packages"})
Q("statistiche carico sistema attuale", ["get_processes"], {"get_processes"})

# === TASKS / NOW (20) ===
Q("task schedulati", ["list_tasks"], {"list_tasks", "read_tasks"})
Q("promemoria attivi", ["list_tasks"], {"list_tasks", "read_tasks"})
Q("pausa task daily-backup", ["set_tasks"], {"set_tasks", "list_tasks"})
Q("cancella task obsoleti", ["delete_tasks"], {"delete_tasks", "list_tasks"})
Q("crea task daily 06:00 pulizia /tmp", ["create_tasks"], {"create_tasks"})
Q("ricordami comprare pane domani 18", ["create_tasks"], {"create_tasks"})
Q("imposta sveglia 7:30", ["create_tasks"], {"create_tasks"})
Q("timer 10 minuti", ["create_tasks"], {"create_tasks"})
Q("ricordami tra un'ora", ["create_tasks"], {"create_tasks"})
Q("alla sera riassunto mail", ["create_tasks"], {"create_tasks"})
Q("storia esecuzioni task daily-clean", ["read_tasks"], {"read_tasks", "list_tasks"})
Q("conta task attivi", ["list_tasks", "compute_entries"], {"list_tasks"})
Q("ultimo task eseguito", ["read_tasks", "sort_entries"], {"read_tasks", "list_tasks"})
Q("ora corrente", ["get_now"], {"get_now"})
Q("che ore sono", ["get_now"], {"get_now"})
Q("data oggi", ["get_now"], {"get_now"})
Q("differenza giorni tra 2026-01-01 e oggi", ["get_now"], {"get_now"})
Q("backup settimanale di /home/roberto domenica 02:00", ["create_tasks"], {"create_tasks"})
Q("ogni mattina mandami appuntamenti via mail", ["create_tasks"], {"create_tasks"})
Q("disabilita task notturno cleanup", ["set_tasks"], {"set_tasks", "list_tasks"})

# === CREDENTIALS (5) ===
Q("elenca credenziali salvate", ["find_credentials"], {"find_credentials"})
Q("credenziali per gmail", ["find_credentials"], {"find_credentials"})
Q("cancella credenziali gmail", ["delete_credentials"], {"delete_credentials"})
Q("aggiorna password account-X", ["set_credentials"], {"set_credentials"})
Q("metadata credenziali scadute", ["find_credentials"], {"find_credentials"})

# === COMPLEX MULTI-DOMAIN (50) ===
Q("crea evento per ogni mail con 'meeting'", ["read_messages", "create_events"], {"read_messages"})
Q("scrivi report con mail e appuntamenti settimana", ["read_messages", "read_events", "write_files_doc"], {"read_messages", "read_events"})
Q("invita tutti i contatti family a evento birthday", ["read_persons", "create_events"], {"read_persons", "read_contacts"})
Q("manda lista mail oggi a Roberto via mail", ["read_messages", "send_messages"], {"read_messages"})
Q("agenda condivisa con Lucia per oggi", ["read_events", "read_persons"], {"read_events"})
Q("foto di Marco al mare 2024", ["find_persons_indices"], {"find_persons_indices", "find_images_indices"})
Q("ultima foto di Lucia con location", ["find_persons_indices", "sort_entries"], {"find_persons_indices"})
Q("conta foto persone famiglia 2024 per mese", ["find_persons_indices", "group_entries"], {"find_persons_indices"})
Q("scarica primo pdf su 'machine learning' da google", ["find_urls", "get_urls"], {"find_urls"})
Q("estrai testo da github metnos readme.md", ["find_urls", "read_urls_html"], {"find_urls", "read_urls_html"})
Q("estrai email da pdf in /tmp", ["find_files", "read_files"], {"find_files"})
Q("genera report excel con conteggio mail per mittente", ["read_messages", "group_entries", "write_files_spreadsheet"], {"read_messages"})
Q("ordina contatti per ultimo contatto via mail", ["read_persons", "sort_entries"], {"read_persons", "read_contacts"})
Q("file Python più di 1000 righe in /opt/metnos", ["find_files", "compute_files_loc"], {"find_files", "compute_files_loc"})
Q("statistiche righe codice per linguaggio in /opt/metnos", ["find_files", "compute_files_loc", "group_entries"], {"find_files", "compute_files_loc"})
Q("cartelle figlie di /home con più di 5GB", ["find_dirs", "compute_entries"], {"find_dirs", "find_files"})
Q("trova file duplicati per hash e cancellali", ["find_files", "compute_signatures", "delete_files"], {"find_files"})
Q("mail da indirizzi non in rubrica classifica come spam", ["read_messages", "classify_entries"], {"read_messages"})
Q("converte tutti i raw in /Foto/2024 in jpg", ["find_files", "change_files_format"], {"find_files"})
Q("apri tutti i pdf dei progetti 2025", ["find_files", "read_files"], {"find_files"})
Q("scarica immagini da pagina web e indicizzale", ["read_urls_html", "get_urls", "create_images_indices"], {"read_urls_html"})
Q("eventi senza partecipanti", ["read_events"], {"read_events"})
Q("mail senza risposta da 7 giorni", ["read_messages"], {"read_messages"})
Q("file pdf non aperti negli ultimi 6 mesi", ["find_files"], {"find_files"})
Q("backup settimanale Documenti in zip", ["create_tasks"], {"create_tasks"})
Q("ogni lunedì pulizia /tmp", ["create_tasks"], {"create_tasks"})
Q("statistiche mail mensili come spreadsheet", ["read_messages", "group_entries", "write_files_spreadsheet"], {"read_messages"})
Q("genera spreadsheet eventi settimana per persona", ["read_events", "group_entries", "write_files_spreadsheet"], {"read_events"})
Q("salva snapshot di tutte le mail di oggi in /tmp/dump", ["read_messages", "write_files"], {"read_messages"})
Q("scarica readme di repo github e salvalo in /tmp", ["read_urls_html", "write_files"], {"read_urls_html"})
Q("conta righe codice python in repo e salva report", ["find_files", "compute_files_loc", "write_files_doc"], {"find_files", "compute_files_loc"})
Q("trova mail allegato pdf e salva in /tmp/allegati", ["read_messages", "write_files"], {"read_messages"})
Q("ordina mail per dimensione decrescente prime 10", ["read_messages", "sort_entries"], {"read_messages"})
Q("eventi più lunghi della settimana classificali per tipo", ["read_events", "sort_entries", "classify_entries"], {"read_events"})
Q("controlla github metnos ultimi 5 commit", ["read_urls_html"], {"read_urls_html"})
Q("status build di repo github metnos", ["read_urls_html"], {"read_urls_html"})
Q("apri ultima release github metnos in /tmp", ["read_urls_html", "write_files"], {"read_urls_html"})
Q("mail simili a 'fattura 2024' classifica per progetto", ["read_messages", "classify_entries"], {"read_messages"})
Q("genera invito evento birthday come pdf", ["create_events", "write_files_doc"], {"create_events"})
Q("scrivi documento con riassunto giornata", ["read_events", "read_messages", "write_files_doc"], {"read_events", "read_messages"})
Q("crea task per ogni evento di domani", ["read_events", "create_tasks"], {"read_events"})
Q("aggiorna spreadsheet spese mensile con dati banca pdf", ["find_files", "read_files", "write_files_spreadsheet"], {"find_files"})
Q("file pdf scaduti da archiviare in zip", ["find_files"], {"find_files"})
Q("trova foto del compleanno scorso e mandale via mail", ["find_images_indices", "send_messages"], {"find_images_indices", "find_persons_indices"})
Q("foto persone non in rubrica", ["find_persons_indices", "filter_entries"], {"find_persons_indices"})
Q("eventi che si sovrappongono questo mese segnala", ["read_events", "compare_entries"], {"read_events"})
Q("mail importanti ma non lette filtrate", ["read_messages", "filter_entries"], {"read_messages"})
Q("genera pdf report eventi mensili", ["read_events", "write_files_doc"], {"read_events"})
Q("ordina file Downloads per data modifica desc", ["find_files", "sort_entries"], {"find_files"})
Q("trova primo url libero per dominio metnos", ["find_urls"], {"find_urls"})

# === GITHUB-SPECIFIC via read_urls_html (15) ===
Q("issue aperti su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("ultimo commit su main di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("pull request da fare review su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("releases pubblicate su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("contributors di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("test falliti ultima settimana su CI di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("compare branch main vs dev su https://github.com/x/metnos", ["read_urls_html", "compare_entries"], {"read_urls_html"})
Q("statistiche commit per autore di https://github.com/x/metnos", ["read_urls_html", "group_entries"], {"read_urls_html"})
Q("storia release ultimi 6 mesi di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("issue label 'bug' su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("activity recente su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("watchers e stars di https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("controlla CI status main su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("apri ultima release github e salva note in /tmp/notes.md", ["read_urls_html", "write_files"], {"read_urls_html"})
Q("scarica file source da https://github.com/x/metnos/blob/X.py", ["read_urls_html"], {"read_urls_html", "get_urls"})

# === GitHub WORKFLOW (ADR 0141 planned, NO github_* executors today) ===
# Catalog può fare READ-only via read_urls_html (web scrape github.com).
# Catalog NON può fare WRITE (POST API comment/close) → request_new_executor.

# READ-ONLY (risolvibili oggi via read_urls_html scraping)
Q("rileva nuove issue su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html", "find_urls"})
Q("scopri issue aperte su https://github.com/x/metnos negli ultimi 7 giorni", ["read_urls_html"], {"read_urls_html", "find_urls"})
Q("monitora issue label 'bug' su https://github.com/x/metnos", ["read_urls_html"], {"read_urls_html"})
Q("riassumi le issue di github metnos e mandami report email", ["read_urls_html", "describe_entries", "send_messages"], {"read_urls_html"})
Q("genera report admin con dettaglio issue aperti su github metnos", ["read_urls_html", "write_files_doc"], {"read_urls_html"})
Q("analizza issue #456 di github metnos e proponi soluzione", ["read_urls_html", "describe_entries"], {"read_urls_html"})
Q("estrai testo da issue #123 e classifica per severity", ["read_urls_html", "classify_entries"], {"read_urls_html"})
Q("filtra issue github per autore 'roberto'", ["read_urls_html", "filter_entries"], {"read_urls_html"})
Q("conta issue chiuse questo mese su github metnos", ["read_urls_html", "compute_entries"], {"read_urls_html"})
Q("ordina issue github per priorità", ["read_urls_html", "sort_entries"], {"read_urls_html"})
Q("raggruppa issue github per label", ["read_urls_html", "group_entries"], {"read_urls_html"})
Q("analizza con LLM le ultime 5 issue github e suggerisci priorità", ["read_urls_html", "describe_entries"], {"read_urls_html"})
Q("scarica issue github e indicizza per ricerca semantica", ["read_urls_html", "create_files_doc"], {"read_urls_html"})
Q("statistiche issue github ultimo trimestre come spreadsheet", ["read_urls_html", "write_files_spreadsheet"], {"read_urls_html"})

# SCHEDULING + READ (risolvibili: create_tasks + read_urls_html)
Q("crea task settimanale per check issue github metnos", ["create_tasks"], {"create_tasks"})
Q("notifica admin se issue critica aperta su github", ["create_tasks", "send_messages"], {"create_tasks"})

# WRITE-TO-GITHUB (CATALOG GAP — richiede new executor coerente §2.2)
# Es. set_messages_github / send_messages_github / write_files_github
Q("rispondi all'issue #123 su https://github.com/x/metnos con 'thanks for reporting'", ["request_new_executor"], {"request_new_executor"})
Q("commenta issue #456 con 'fix in progress'", ["request_new_executor"], {"request_new_executor"})
Q("chiudi issue #789 su github metnos", ["request_new_executor"], {"request_new_executor"})
Q("auto-rispondi a nuove issue github con template benvenuto", ["request_new_executor"], {"request_new_executor", "create_tasks"})

# MULTI-STAGE CATALOG GAP (path multi-step con gap intermedio, primo step OK)
Q("leggi mail di Mario, riassumi e pubblica come issue github", ["read_messages", "describe_entries", "request_new_executor"], {"read_messages"})
Q("scarica feed RSS phoronix e crea task per ogni notizia importante", ["get_urls", "filter_entries", "create_tasks"], {"get_urls", "find_urls"})
Q("estrai codice da file github metnos e indicizza per ricerca", ["read_urls_html", "create_files_doc", "request_new_executor"], {"read_urls_html"})
Q("ogni 5 min cerca nuove issue github e se urgenti rispondi auto", ["create_tasks"], {"create_tasks"})
Q("genera CV da mie esperienze in github commits", ["read_urls_html", "describe_entries", "write_files_doc"], {"read_urls_html"})
Q("riassumi 10 issue github più discusse e mandami via mail", ["read_urls_html", "sort_entries", "describe_entries", "send_messages"], {"read_urls_html"})
Q("scarica logs CI di repo github e classifica errori per tipo", ["read_urls_html", "classify_entries"], {"read_urls_html"})
Q("crea pdf report stato issue github settimanale e invia a admin", ["create_tasks"], {"create_tasks", "read_urls_html"})
Q("leggi commit recenti github metnos e estrai TODO menzionati", ["read_urls_html", "filter_texts_lines"], {"read_urls_html"})
Q("notifica via mail quando arriva nuova PR su github metnos", ["create_tasks", "send_messages"], {"create_tasks"})

# MULTI-STAGE GAP fuori github (per varietà)
Q("scarica nuovi pdf da arxiv RSS e indicizza per topic", ["find_urls", "read_urls_pdf", "create_files_doc"], {"find_urls"})
Q("ogni lunedì cerca update sicurezza su sito CVE e mandami report", ["create_tasks"], {"create_tasks"})
Q("monitora prezzo prodotto amazon e avvisa se scende sotto soglia", ["create_tasks", "read_urls_html", "send_messages"], {"create_tasks", "read_urls_html"})
Q("traccia stato spedizione DHL e notifica quando consegnato", ["create_tasks", "read_urls_html"], {"create_tasks", "read_urls_html"})
Q("riassumi ogni mattina le news del giorno e mandami via mail", ["create_tasks"], {"create_tasks"})

# === GOOGLE WORKSPACE via files_doc/spreadsheet (15) ===
Q("crea documento google 'piano lavoro 2026'", ["create_files_doc"], {"create_files_doc"})
Q("crea spreadsheet 'budget mensile'", ["create_files_spreadsheet"], {"create_files_spreadsheet"})
Q("apri https://docs.google.com/document/d/X", ["read_urls_html"], {"read_urls_html", "read_files_doc"})
Q("apri https://docs.google.com/spreadsheets/d/Y", ["read_urls_html"], {"read_urls_html", "read_files_spreadsheet"})
Q("aggiungi riga al foglio /home/docs/spese.xlsx", ["read_files_spreadsheet", "write_files_spreadsheet"], {"read_files_spreadsheet"})
Q("scrivi nuovo doc con appuntamenti settimana", ["read_events", "create_files_doc"], {"read_events"})
Q("scrivi nuovo doc con report mail mensili", ["read_messages", "create_files_doc"], {"read_messages"})
Q("calcola somma colonna B in /tmp/dati.xlsx", ["read_files_spreadsheet", "compute_entries"], {"read_files_spreadsheet"})
Q("filtra righe spese > 100 EUR in /home/spese.xlsx", ["read_files_spreadsheet", "filter_entries"], {"read_files_spreadsheet"})
Q("ordina foglio /tmp/data.xlsx per colonna data", ["read_files_spreadsheet", "sort_entries"], {"read_files_spreadsheet"})
Q("crea pdf da documento /home/relazione.docx", ["change_files_format"], {"change_files_format", "read_files_doc"})
Q("converte /tmp/foglio.xlsx in csv", ["change_files_format"], {"change_files_format"})
Q("salva ultime 10 mail come righe nel foglio /home/log.xlsx", ["read_messages", "write_files_spreadsheet"], {"read_messages"})
Q("genera pdf con eventi mensili", ["read_events", "write_files_doc"], {"read_events"})
Q("scrivi documento con riassunto giornata e appuntamenti", ["read_events", "read_messages", "write_files_doc"], {"read_events", "read_messages"})


# === EXTRA 70 (variazioni linguistiche + edge complex) ===
Q("apri /home/user/documento.pdf", ["read_files"], {"read_files"})
Q("leggi /tmp/file.txt", ["read_files"], {"read_files"})
Q("contenuto della cartella /home", ["list_dirs"], {"list_dirs", "find_files"})
Q("file più piccoli di 1KB in /tmp", ["find_files"], {"find_files"})
Q("file più grandi di 1GB in /var", ["find_files"], {"find_files"})
Q("estensione file più comune in /home", ["find_files", "group_entries"], {"find_files"})
Q("classifica file per tipo MIME in /tmp", ["find_files", "classify_entries"], {"find_files"})
Q("hash md5 file /tmp/x.iso", ["compute_signatures"], {"compute_signatures"})
Q("crea backup /home/roberto in /tmp/back", ["find_files", "move_files"], {"find_files"})
Q("script ruby in /opt", ["find_files"], {"find_files"})
Q("mail da clienti non gestite", ["read_messages"], {"read_messages"})
Q("contatti dell'azienda Alpha", ["read_persons"], {"read_persons", "read_contacts"})
Q("mail di carlo questo mese", ["read_messages"], {"read_messages"})
Q("mail di importo > 100EUR (fatture)", ["read_messages"], {"read_messages"})
Q("eventi della settimana classifica per tipo", ["read_events", "classify_entries"], {"read_events"})
Q("primo evento del giorno con location", ["read_events", "sort_entries"], {"read_events"})
Q("eventi privati questa settimana", ["read_events"], {"read_events"})
Q("appuntamenti con allegati", ["read_events"], {"read_events"})
Q("evento più frequente del mese", ["read_events", "group_entries", "sort_entries"], {"read_events"})
Q("ricorrenze del mese", ["read_events"], {"read_events"})
Q("foto location Roma 2024", ["find_images_indices"], {"find_images_indices"})
Q("estrai EXIF da tutte le foto in /home/Foto", ["find_files", "get_files"], {"find_files"})
Q("aggiorna indice foto dopo aggiunte", ["create_images_indices"], {"create_images_indices"})
Q("foto con Lucia a Roma 2024", ["find_persons_indices"], {"find_persons_indices"})
Q("conta volti per persona indicizzata", ["find_persons_indices", "compute_entries", "group_entries"], {"find_persons_indices"})
Q("cerca su web 'come installare docker linux'", ["find_urls"], {"find_urls"})
Q("apri pagina https://blog.python.org", ["read_urls_html"], {"read_urls_html"})
Q("estrai sezione 'Installation' da https://docs.python.org/install", ["read_urls_html"], {"read_urls_html"})
Q("ultimi articoli su phoronix", ["find_urls"], {"find_urls"})
Q("scarica RFC 2616 da ietf.org", ["find_urls", "get_urls"], {"find_urls"})
Q("estrai link da https://news.ycombinator.com", ["read_urls_html"], {"read_urls_html"})
Q("Wikipedia voce su 'Information Retrieval'", ["find_urls", "read_urls_html"], {"find_urls"})
Q("PDF su 'graph search algorithms' su arxiv", ["find_urls", "read_urls_pdf"], {"find_urls"})
Q("issue github per progetto torchvision", ["read_urls_html"], {"read_urls_html"})
Q("scarica readme.md da github mlflow", ["read_urls_html"], {"read_urls_html"})
Q("foglio /home/calendari.xlsx ordina per data", ["read_files_spreadsheet", "sort_entries"], {"read_files_spreadsheet"})
Q("calcola media colonna 'spesa' in /home/spese.xlsx", ["read_files_spreadsheet", "compute_entries"], {"read_files_spreadsheet"})
Q("filtra colonna 'status'='ok' in /tmp/log.csv", ["read_files_csv", "filter_entries"], {"read_files_csv"})
Q("converte /tmp/dati.csv in xlsx", ["change_files_format"], {"change_files_format"})
Q("scrivi documento con riepilogo mensile", ["create_files_doc"], {"create_files_doc", "write_files_doc"})
Q("apri documento pdf più recente", ["find_files", "sort_entries", "read_files"], {"find_files"})
Q("statistiche file per estensione", ["find_files", "group_entries"], {"find_files"})
Q("totale dimensione per cartella in /home", ["find_dirs", "compute_entries"], {"find_dirs", "find_files"})
Q("conta script in /opt/metnos/install per linguaggio", ["find_files", "group_entries"], {"find_files"})
Q("immagini più nuove di un mese in /home/Foto", ["find_images_indices"], {"find_images_indices", "find_files"})
Q("conta foto per anno scatto", ["find_images_indices", "group_entries"], {"find_images_indices"})
Q("salva contatti in /tmp/contacts.csv", ["read_persons", "write_files"], {"read_persons", "read_contacts"})
Q("export mail di oggi in /tmp/mails.json", ["read_messages", "write_files"], {"read_messages"})
Q("ultime modifiche files in /opt/metnos", ["find_files", "sort_entries"], {"find_files"})
Q("script python con più di 500 righe in /opt/metnos", ["find_files", "compute_files_loc", "filter_entries"], {"find_files", "compute_files_loc"})
Q("contatti senza telefono", ["read_persons"], {"read_persons", "read_contacts"})
Q("foto senza tag di persona", ["find_images_indices"], {"find_images_indices"})
Q("mail con allegati > 10MB", ["read_messages"], {"read_messages"})
Q("eventi senza descrizione", ["read_events"], {"read_events"})
Q("eventi che ho creato io ultimo mese", ["read_events"], {"read_events"})
Q("manda mail di update a tutti i clienti", ["read_persons", "send_messages"], {"read_persons", "read_contacts"})
Q("crea cartella per ogni cliente in /home/clienti", ["read_persons", "create_dirs"], {"read_persons"})
Q("rinomina file /tmp/a.txt in /tmp/b.txt", ["move_files"], {"move_files"})
Q("rinomina file in /tmp con pattern 'old_*' a 'new_*'", ["find_files", "move_files"], {"find_files"})
Q("trova file modificati da utente roberto in /tmp", ["find_files"], {"find_files"})
Q("script bash in cron daily", ["find_files"], {"find_files"})
Q("estrai tabella da pdf /tmp/report.pdf", ["read_files"], {"read_files"})
Q("salva mail allegati pdf in /tmp/allegati", ["read_messages", "write_files"], {"read_messages"})
Q("genera spreadsheet con statistiche file per dir", ["find_files", "group_entries", "write_files_spreadsheet"], {"find_files"})
Q("invia mail con link a documento /home/X.pdf", ["read_files", "send_messages"], {"read_files"})
Q("salva agenda settimana come pdf", ["read_events", "write_files_doc"], {"read_events"})
Q("crea evento per ogni task pendente", ["list_tasks", "create_events"], {"list_tasks", "read_tasks"})
Q("ricorda di rispondere a mail di lucia", ["read_messages", "create_tasks"], {"read_messages"})
Q("cancella task completati da una settimana", ["list_tasks", "delete_tasks"], {"list_tasks", "read_tasks"})
Q("crea task ricorrente daily backup foto", ["create_tasks"], {"create_tasks"})
Q("alle 18 manda riassunto della giornata via mail", ["create_tasks"], {"create_tasks"})

# === Sanity check ===
if __name__ == "__main__":
    n = len(TEST_QUERIES_500)
    print(f"Total queries: {n}")
    verbs = set()
    for t in TEST_QUERIES_500:
        for e in t["expected_path"]:
            if "_" in e:
                verbs.add(e.split("_")[0])
    print(f"Distinct expected verbs: {sorted(verbs)}")
    # show object distribution
    from collections import Counter
    objs = Counter()
    for t in TEST_QUERIES_500:
        for e in t["expected_path"]:
            if "_" in e:
                parts = e.split("_", 1)
                if len(parts) > 1:
                    objs[parts[1].split("_")[0]] += 1
    print("Object distribution:")
    for o, c in objs.most_common():
        print(f"  {c:4d}× {o}")
