"""Immutable Birth owner, sealed-module and coordinator authority facts."""
from __future__ import annotations

from dataclasses import dataclass

from contract_boundary_policy_types import (
    ContractBoundaryPolicyError, canonical_names_v1, require_scope_key_v1,
)


@dataclass(frozen=True, slots=True)
class BirthAuthorityPolicyV1:
    owner: str
    sealed_modules: tuple[str, ...]
    coordinator_store_owners: tuple[str, ...]

    def __post_init__(self) -> None:
        require_scope_key_v1(self.owner, field="birth_owner")
        canonical_names_v1(self.sealed_modules, field="sealed_modules")
        canonical_names_v1(
            self.coordinator_store_owners, field="coordinator_store_owners",
        )
        for scope in self.coordinator_store_owners:
            require_scope_key_v1(scope, field="coordinator_store_owner")
        owner_path = self.owner.split(":", 1)[0]
        if owner_path not in self.sealed_modules:
            raise ContractBoundaryPolicyError(
                "boundary_policy_invalid:birth_owner_not_sealed"
            )


BIRTH_AUTHORITY_POLICY_V1 = BirthAuthorityPolicyV1(
    owner='runtime/executor_birth_operational.py:birth_executor',
    sealed_modules=(
        'runtime/contract_store.py',
        'runtime/executor_birth.py',
        'runtime/executor_birth_commit_publisher.py',
        'runtime/executor_birth_operational.py',
        'runtime/executor_birth_ownership_coordinator.py',
        'runtime/executor_birth_ownership_cutover.py',
        'runtime/executor_birth_preflight_attestation_store.py',
        'runtime/executor_birth_preflight_store_authority.py',
        'runtime/executor_birth_reattestation.py',
        'runtime/executor_birth_transition_chain_policy.py',
        'runtime/executor_birth_transition_gate.py',
        'runtime/executor_birth_transition_receipts.py',
        'runtime/sign.py',
    ),
    coordinator_store_owners=(
        'install/birth_authority_provisioner.py:_publish_initial_predecessor_v2',
        'install/birth_ownership_authority_provisioner.py:_discard_temporary',
        'install/birth_ownership_authority_provisioner.py:_load_or_create_pair',
        'install/birth_ownership_authority_provisioner.py:_provision_ownership_authorities_at_v1',
        'install/birth_ownership_authority_provisioner.py:_provision_ownership_authorities_locked_v1',
        'install/birth_ownership_authority_provisioner.py:_provisioning_lock',
        'install/birth_ownership_authority_provisioner.py:_publish_no_replace',
        'install/birth_ownership_authority_provisioner.py:_sync_directory',
        'install/birth_ownership_authority_provisioner.py:_write_exclusive',
        'install/birth_ownership_authority_provisioner.py:provision_root_ownership_authorities_v1',
        'install/executor_birth_distribution_release.py:build_and_install_received_source_v1',
        'install/executor_birth_python_environment_posix.py:_ensure_core_v1',
        'install/executor_birth_python_environment_posix.py:_seal_tree_v1',
        'install/executor_birth_python_environment_posix.py:ensure_python_environment_for_test_v1',
        'install/executor_birth_python_environment_posix.py:ensure_python_environment_v1',
        'install/executor_birth_source_receiver.py:<module>',
        'install/executor_birth_source_receiver.py:_copy_source_file_v1',
        'install/executor_birth_source_receiver.py:_copy_source_file_v1.copied_chunks',
        'install/executor_birth_source_receiver.py:_create_private_directory_v1',
        'install/executor_birth_source_receiver.py:_create_source_directories_v1',
        'install/executor_birth_source_receiver.py:_ensure_child_directory_v1',
        'install/executor_birth_source_receiver.py:_load_received_source_locked_core_v1',
        'install/executor_birth_source_receiver.py:_load_received_source_with_product_session_v1',
        'install/executor_birth_source_receiver.py:_load_received_source_with_test_session_v1',
        'install/executor_birth_source_receiver.py:_open_received_tree_at_v1',
        'install/executor_birth_source_receiver.py:_receive_source_for_test_v1',
        'install/executor_birth_source_receiver.py:_receive_source_locked_core_v1',
        'install/executor_birth_source_receiver.py:_receive_source_v1',
        'install/executor_birth_source_receiver.py:_receive_source_with_product_session_v1',
        'install/executor_birth_source_receiver.py:_receive_source_with_test_session_v1',
        'install/executor_birth_source_receiver.py:_recover_receive_residue_v1',
        'install/executor_birth_source_receiver.py:_remove_owned_tree_at_v1',
        'install/executor_birth_source_receiver.py:_rename_no_replace_v1',
        'install/executor_birth_source_receiver.py:_seal_temporary_directories_v1',
        'install/executor_birth_source_receiver.py:_verify_received_tree_fd_v1',
        'install/executor_birth_source_receiver.py:_write_all_v1',
        'install/executor_birth_source_receiver.py:_write_descriptor_v1',
        'install/executor_birth_source_receiver.py:main',
        'install/executor_birth_startup_gate.py:_install_startup_gate_core_v1',
        'install/executor_birth_startup_gate.py:_install_startup_gate_for_test_v1',
        'install/executor_birth_startup_gate.py:install_startup_gate_v1',
        'install/executor_birth_startup_prerequisite.py:_finish_temporary_v1',
        'install/executor_birth_startup_prerequisite.py:_publish_core_v1',
        'install/executor_birth_startup_prerequisite.py:_publish_startup_prerequisite_for_test_v2',
        'install/executor_birth_startup_prerequisite.py:_publish_startup_prerequisite_locked_v2',
        'install/executor_birth_systemd.py:_install_group6_administrative_for_test_v1',
        'install/executor_birth_systemd.py:_install_locked_core_v1',
        'install/executor_birth_systemd.py:_install_signed_isolated_systemd_for_test_v1',
        'install/executor_birth_systemd.py:_open_parent_v1',
        'install/executor_birth_systemd.py:_publish_administrative_tree_v1',
        'install/executor_birth_systemd.py:_publish_isolated_units_for_test_v1',
        'install/executor_birth_systemd.py:install_group6_administrative_v1',
        'install/executor_birth_transition.py:<module>',
        'install/executor_birth_transition.py:deploy_source_v1',
        'install/executor_birth_transition.py:main',
        'runtime/executor_birth_commit_publisher.py:_BirthCommitPublisher._persist_current_reattestation',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore._append_pair',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore._update_required_head_locked',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore.append_authenticated_build',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore.append_context_transition',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore.append_cutover',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore.append_head',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore.initialize',
        'runtime/executor_birth_ownership_chain.py:OwnershipChainStore.update_required_head',
        'runtime/executor_birth_ownership_chain.py:_OwnershipChainStoreForTest._initialize_with_authorities',
        'runtime/executor_birth_ownership_chain.py:_ensure_exact_directory_v1',
        'runtime/executor_birth_ownership_chain.py:_ensure_product_directory_v1',
        'runtime/executor_birth_ownership_chain.py:_inspect_ownership_chain_state_core_v1',
        'runtime/executor_birth_ownership_chain.py:_inspect_ownership_chain_state_for_test_v1',
        'runtime/executor_birth_ownership_chain.py:_replace_required_pointer',
        'runtime/executor_birth_ownership_chain.py:_required_head_lock',
        'runtime/executor_birth_ownership_chain.py:inspect_ownership_chain_state_v1',
        'runtime/executor_birth_ownership_coordinator.py:OwnershipCoordinatorJournalV1.append',
        'runtime/executor_birth_ownership_coordinator.py:OwnershipCoordinatorJournalV1.load',
        'runtime/executor_birth_ownership_coordinator.py:_DeploymentLockLeaseV1',
        'runtime/executor_birth_ownership_coordinator.py:_LockedOwnershipCoordinatorGraphSnapshotV2',
        'runtime/executor_birth_ownership_coordinator.py:_OwnershipCoordinatorTransactionJournalV2.__init__',
        'runtime/executor_birth_ownership_coordinator.py:_OwnershipCoordinatorTransactionJournalV2._append_initial',
        'runtime/executor_birth_ownership_coordinator.py:_OwnershipCoordinatorTransactionJournalV2._committed',
        'runtime/executor_birth_ownership_coordinator.py:_OwnershipCoordinatorTransactionJournalV2._inventory',
        'runtime/executor_birth_ownership_coordinator.py:_OwnershipCoordinatorTransactionJournalV2.append_transaction_record',
        'runtime/executor_birth_ownership_coordinator.py:_append_coordinator_record_v1',
        'runtime/executor_birth_ownership_coordinator.py:_append_ownership_transaction_locked_for_test_v2',
        'runtime/executor_birth_ownership_coordinator.py:_append_ownership_transaction_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_append_prepared_transition_locked_for_test_v2',
        'runtime/executor_birth_ownership_coordinator.py:_append_prepared_transition_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_append_receipts_complete',
        'runtime/executor_birth_ownership_coordinator.py:_append_receipts_complete_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_build_locked_coordinator_graph_registry_v2.require_issued',
        'runtime/executor_birth_ownership_coordinator.py:_build_locked_coordinator_graph_registry_v2.resolve_issued',
        'runtime/executor_birth_ownership_coordinator.py:_completed_transition_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_certificate_boundary_core_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_certificate_boundary_locked_for_test_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_certificate_boundary_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_certificate_boundary_locked_v2.observe_certificate_graph',
        'runtime/executor_birth_ownership_coordinator.py:_cross_head_boundary_locked_for_test_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_head_boundary_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_head_boundary_locked_v2.observe_head_graph',
        'runtime/executor_birth_ownership_coordinator.py:_cross_preflight_boundary_locked_for_test_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_preflight_boundary_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_cross_preflight_boundary_locked_v2.observe_preflight_graph',
        'runtime/executor_birth_ownership_coordinator.py:_decode_record',
        'runtime/executor_birth_ownership_coordinator.py:_decode_record_v2',
        'runtime/executor_birth_ownership_coordinator.py:_deployment_lock_at_v1',
        'runtime/executor_birth_ownership_coordinator.py:_deployment_lock_for_test_v1',
        'runtime/executor_birth_ownership_coordinator.py:_deployment_lock_v1',
        'runtime/executor_birth_ownership_coordinator.py:_ensure_coordinator_child_directory_v2',
        'runtime/executor_birth_ownership_coordinator.py:_observe_dominant_identity_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_prepare_under_maintenance_v1',
        'runtime/executor_birth_ownership_coordinator.py:_proof_from_values',
        'runtime/executor_birth_ownership_coordinator.py:_publish_certificate_material_v2',
        'runtime/executor_birth_ownership_coordinator.py:_publish_certificate_with_prerequisite_v1',
        'runtime/executor_birth_ownership_coordinator.py:_publish_context_transition_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_publish_control_no_replace_v2',
        'runtime/executor_birth_ownership_coordinator.py:_publish_test_preflight_attestation_v2',
        'runtime/executor_birth_ownership_coordinator.py:_publish_transaction_directory_no_replace_v2',
        'runtime/executor_birth_ownership_coordinator.py:_read_staged_transaction_directory_v2',
        'runtime/executor_birth_ownership_coordinator.py:_require_locked_coordinator_graph_snapshot_v2',
        'runtime/executor_birth_ownership_coordinator.py:_reserve_transition_edge_core_v2',
        'runtime/executor_birth_ownership_coordinator.py:_reserve_transition_edge_locked_for_test_v2',
        'runtime/executor_birth_ownership_coordinator.py:_reserve_transition_edge_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_resolve_ownership_coordinator_locked_v2',
        'runtime/executor_birth_ownership_coordinator.py:_transition_edge_locked_v2',
        'runtime/executor_birth_preflight_attestation_store.py:_promote_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_publish_locked_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_publish_preflight_attestation_core_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_publish_preflight_attestation_for_test_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_publish_preflight_attestation_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_recover_both_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_recover_temporary_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_stage_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_sync_unlink_v1',
        'runtime/executor_birth_preflight_attestation_store.py:_write_all_exact_v1',
        'runtime/executor_birth_preflight_store_authority.py:bind_store_mutation_port_v1',
        'runtime/executor_birth_transition_chain_policy.py:_transition_chain_authority_source_v2',
        'runtime/executor_birth_transition_gate.py:_transition_current_enumerator_v2',
        'runtime/executor_birth_transition_gate.py:_transition_gate_snapshot_locked_v2',
    ),
)

__all__ = ["BIRTH_AUTHORITY_POLICY_V1", "BirthAuthorityPolicyV1"]
