"""Public facade and legacy materialization for contract boundary policy."""
from __future__ import annotations

from typing import Mapping

from contract_boundary_api_policy import (
    BOUNDARY_API_OWNERS_V1 as _BOUNDARY_API_OWNERS_V1,
    BOUNDARY_MODULE_OWNERS_V1 as _BOUNDARY_MODULE_OWNERS_V1,
    BOUNDARY_SOURCE_OWNERS_V1 as _BOUNDARY_SOURCE_OWNERS_V1,
)
import contract_boundary_syntax_policy as _syntax


def _materialize_apis_v1() -> dict[str, dict[str, tuple[str, ...]]]:
    return {
        row.owner: {name: capabilities for name, capabilities in row.apis}
        for row in _BOUNDARY_API_OWNERS_V1
    }


def _materialize_modules_v1() -> dict[str, frozenset[str]]:
    return {
        row.owner: frozenset(row.module_names)
        for row in _BOUNDARY_MODULE_OWNERS_V1
    }


def _materialize_source_owners_v1() -> dict[str, str]:
    return {row.path: row.owner for row in _BOUNDARY_SOURCE_OWNERS_V1}


SCHEMA = _syntax.SCHEMA
BIRTH_CLOSED_SCHEMA = _syntax.BIRTH_CLOSED_SCHEMA
BIRTH_CLOSED_GUARD_VERSION = _syntax.BIRTH_CLOSED_GUARD_VERSION
SCAN_ROOTS = _syntax.SCAN_ROOTS
AUTHORING_FILES = _syntax.AUTHORING_FILES
BOUNDARY_LIMITS_V1 = _syntax.BOUNDARY_LIMITS_V1
MAX_BOUNDARY_SOURCE_FILES = _syntax.MAX_BOUNDARY_SOURCE_FILES
MAX_BOUNDARY_SOURCE_BYTES = _syntax.MAX_BOUNDARY_SOURCE_BYTES
MAX_BOUNDARY_TOTAL_SOURCE_BYTES = _syntax.MAX_BOUNDARY_TOTAL_SOURCE_BYTES
MAX_BOUNDARY_AST_NODES = _syntax.MAX_BOUNDARY_AST_NODES
MAX_BOUNDARY_TOTAL_AST_NODES = _syntax.MAX_BOUNDARY_TOTAL_AST_NODES
MAX_BOUNDARY_AST_DEPTH = _syntax.MAX_BOUNDARY_AST_DEPTH
MAX_BOUNDARY_SCOPES = _syntax.MAX_BOUNDARY_SCOPES
MAX_BOUNDARY_CALLS = _syntax.MAX_BOUNDARY_CALLS

BOUNDARY_APIS: Mapping[str, Mapping[str, tuple[str, ...]]] = (
    _materialize_apis_v1()
)
BOUNDARY_MODULES: Mapping[str, frozenset[str]] = _materialize_modules_v1()
BOUNDARY_SOURCE_OWNERS: Mapping[str, str] = _materialize_source_owners_v1()
READ_OPERATIONS = _syntax.READ_OPERATIONS
WRITE_OPERATIONS = _syntax.WRITE_OPERATIONS
PROCESS_CALLS = _syntax.PROCESS_CALLS
DYNAMIC_CODE_LOADER_APIS = _syntax.DYNAMIC_CODE_LOADER_APIS
DYNAMIC_CODE_LOADER_CANONICALS = _syntax.DYNAMIC_CODE_LOADER_CANONICALS
SENSITIVE_FIRST_CLASS_REFERENCES = _syntax.SENSITIVE_FIRST_CLASS_REFERENCES
SENSITIVE_IMPORT_NAMESPACES = _syntax.SENSITIVE_IMPORT_NAMESPACES
SYS_MODULES_EXPOSING_METHODS = _syntax.SYS_MODULES_EXPOSING_METHODS
SYS_MODULES_MUTATING_METHODS = _syntax.SYS_MODULES_MUTATING_METHODS
AUTHENTICATED_EXECUTION_SCOPE = _syntax.AUTHENTICATED_EXECUTION_SCOPE
AUTHENTICATED_PREFLIGHT_EXECUTION_SCOPE = (
    _syntax.AUTHENTICATED_PREFLIGHT_EXECUTION_SCOPE
)
LIVE_READER_FORBIDDEN = _syntax.LIVE_READER_FORBIDDEN
PUBLISH_CAPABILITIES = _syntax.PUBLISH_CAPABILITIES
FLOW_CAPABILITIES = _syntax.FLOW_CAPABILITIES

AUTHORING_NAME_REGEX_V1 = _syntax.AUTHORING_NAME_REGEX_V1
AMBIGUOUS_AUTHORING_ARGUMENT_REGEX_V1 = (
    _syntax.AMBIGUOUS_AUTHORING_ARGUMENT_REGEX_V1
)
STORE_NAME_REGEX_V1 = _syntax.STORE_NAME_REGEX_V1
CONTRACT_SCOPE_REGEX_V1 = _syntax.CONTRACT_SCOPE_REGEX_V1
GENERIC_PATH_NAME_REGEX_V1 = _syntax.GENERIC_PATH_NAME_REGEX_V1
_AUTHORING_NAME_RE = _syntax._AUTHORING_NAME_RE
_AMBIGUOUS_AUTHORING_ARGUMENT_RE = _syntax._AMBIGUOUS_AUTHORING_ARGUMENT_RE
_STORE_NAME_RE = _syntax._STORE_NAME_RE
_CONTRACT_SCOPE_RE = _syntax._CONTRACT_SCOPE_RE
_GENERIC_PATH_NAME_RE = _syntax._GENERIC_PATH_NAME_RE


__all__ = [
    "AMBIGUOUS_AUTHORING_ARGUMENT_REGEX_V1", "AUTHENTICATED_EXECUTION_SCOPE",
    "AUTHENTICATED_PREFLIGHT_EXECUTION_SCOPE", "AUTHORING_FILES",
    "AUTHORING_NAME_REGEX_V1", "BIRTH_CLOSED_GUARD_VERSION",
    "BIRTH_CLOSED_SCHEMA", "BOUNDARY_APIS", "BOUNDARY_LIMITS_V1",
    "BOUNDARY_MODULES", "BOUNDARY_SOURCE_OWNERS", "CONTRACT_SCOPE_REGEX_V1",
    "DYNAMIC_CODE_LOADER_APIS", "DYNAMIC_CODE_LOADER_CANONICALS",
    "FLOW_CAPABILITIES", "GENERIC_PATH_NAME_REGEX_V1",
    "LIVE_READER_FORBIDDEN", "MAX_BOUNDARY_AST_DEPTH",
    "MAX_BOUNDARY_AST_NODES", "MAX_BOUNDARY_CALLS", "MAX_BOUNDARY_SCOPES",
    "MAX_BOUNDARY_SOURCE_BYTES", "MAX_BOUNDARY_SOURCE_FILES",
    "MAX_BOUNDARY_TOTAL_AST_NODES", "MAX_BOUNDARY_TOTAL_SOURCE_BYTES",
    "PROCESS_CALLS", "PUBLISH_CAPABILITIES", "READ_OPERATIONS", "SCAN_ROOTS",
    "SCHEMA", "SENSITIVE_FIRST_CLASS_REFERENCES",
    "SENSITIVE_IMPORT_NAMESPACES", "STORE_NAME_REGEX_V1",
    "SYS_MODULES_EXPOSING_METHODS", "SYS_MODULES_MUTATING_METHODS",
    "WRITE_OPERATIONS",
]
