#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Aggiorna soltanto le chiavi Monitor del seed i18n candidato.

Il replay conserva gli hash della baseline precedente; non sostituisce il DB
e non aggiorna i cataloghi degli utenti. Il runtime li integra al rilascio.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "TITLE": ("Monitor", "Monitor"),
    "OVERVIEW": ("Panoramica", "Overview"),
    "REQUESTS": ("Richieste", "Requests"),
    "MODELS": ("Prestazioni modelli", "Model performance"),
    "REQUEST_DETAIL": ("Dettaglio richiesta", "Request details"),
    "EXECUTORS": ("Executor", "Executors"),
    "SUBTITLE": ("Token, tempi e velocità delle richieste e delle chiamate ai modelli.", "Tokens, durations and speeds of requests and model calls."),
    "OVERVIEW_HELP": ("Andamento delle richieste utente complete e stato della raccolta.", "Complete user request trends and collection health."),
    "MODELS_HELP": ("Confronto delle chiamate LLM per nome logico, modello fisico e fornitore.", "Compare LLM calls by logical name, physical model and provider."),
    "CALL_SPEED_HELP": ("Velocità media chiamata: token generati ÷ tempo dall'inizio alla fine, inclusi prefill, generazione, coda e trasporto. Media ponderata: somma dei token ÷ somma delle durate delle chiamate valide.", "Mean call speed: generated tokens ÷ time from start to finish, including prefill, generation, queueing and transport. Weighted mean: total tokens ÷ total durations of valid calls."),
    "REQUEST_SPEED_HELP": ("Token generati da tutte le chiamate LLM ÷ durata totale delle richieste concluse, comprese operazioni e attese.", "Tokens generated by all LLM calls ÷ total duration of completed requests, including operations and waits."),
    "TOTAL_TIME_HELP": ("Dall'avvio della richiesta alla conclusione, comprese le attese.", "From request start to completion, including waits."),
    "NAVIGATION": ("Viste del Monitor", "Monitor views"),
    "FILTERS": ("Filtri del Monitor", "Monitor filters"),
    "PERIOD": ("Periodo", "Period"),
    "PERIOD_TODAY": ("Oggi", "Today"),
    "PERIOD_24H": ("Ultime 24 ore", "Last 24 hours"),
    "PERIOD_7D": ("Ultimi 7 giorni", "Last 7 days"),
    "PERIOD_CUSTOM": ("Personalizzato", "Custom"),
    "CHANNEL": ("Canale", "Channel"),
    "STATUS": ("Stato", "Status"),
    "OUTCOME": ("Esito", "Outcome"),
    "OUTCOME_OK": ("Riuscita", "Succeeded"),
    "LOGICAL_MODEL": ("Nome logico", "Logical name"),
    "PHYSICAL_MODEL": ("Modello fisico", "Physical model"),
    "MODEL_GROUPING": ("Raggruppamento", "Grouping"),
    "GROUP_LOGICAL_PHYSICAL": ("Livello e modello fisico", "Logical level and physical model"),
    "GROUP_PHYSICAL": ("Solo modello fisico", "Physical model only"),
    "MODEL_GROUPING_HELP": ("La vista per modello fisico somma le chiamate dei livelli selezionati, mantenendo separati i fornitori e le identità fisiche. Le velocità sono calcolate dalle somme di token e durate valide.", "The physical model view sums calls from the selected logical levels, keeping providers and physical identities separate. Speeds use sums of tokens and valid durations."),
    "BUCKET_INTERVAL": ("Intervallo", "Interval"),
    "OBSERVED_FORMULA": ("Formula osservata", "Observed formula"),
    "PROVIDER": ("Fornitore", "Provider"),
    "ORIGIN": ("Origine", "Origin"),
    "ORIGIN_INTERACTIVE": ("Interattiva", "Interactive"),
    "ORIGIN_BACKGROUND": ("In background", "Background"),
    "ORIGIN_TEST": ("Test", "Test"),
    "ALL": ("Tutti", "All"),
    "APPLY": ("Applica filtri", "Apply filters"),
    "MORE_FILTERS": ("Altri filtri e intervallo personalizzato", "More filters and custom range"),
    "FROM_UTC": ("Da · UTC", "From · UTC"),
    "TO_UTC": ("A · UTC", "To · UTC"),
    "DATE_PLACEHOLDER": ("2026-10-08T00:00:00Z", "2026-10-08T00:00:00Z"),
    "RANGE_HELP": ("Per un intervallo personalizzato usa date UTC: anno-mese-giornoTora:minuti:secondiZ. L'inizio è incluso, la fine esclusa; massimo 90 giorni.", "For a custom range use UTC dates: year-month-dayThour:minute:secondZ. The start is inclusive and the end exclusive; maximum 90 days."),
    "MODEL_FILTER_SCOPE": ("I filtri dei modelli selezionano solo le chiamate corrispondenti.", "Model filters select only the matching calls."),
    "REQUEST_FILTER_SCOPE": ("I filtri dei modelli selezionano le richieste che li contengono; i totali comprendono tutte le chiamate di quelle richieste.", "Model filters select requests containing those models; totals include all calls in those requests."),
    "BACKGROUND_EXCLUDED": ("Le origini in background e di test sono escluse quando non selezionate.", "Background and test origins are excluded unless selected."),
    "SUMMARY": ("Riepilogo del periodo filtrato", "Summary of the filtered period"),
    "COMPLETED_REQUESTS": ("Richieste concluse", "Completed requests"),
    "REQUEST_COUNT": ("Richieste osservate", "Observed requests"),
    "CALLS": ("Chiamate", "Calls"),
    "ERRORS": ("Errori", "Errors"),
    "INPUT_TOKENS": ("Token ingresso", "Input tokens"),
    "OUTPUT_TOKENS": ("Token uscita", "Output tokens"),
    "KNOWN_CALLS": ("Chiamate con misura", "Calls with a measurement"),
    "ACTIVE_MEDIAN": ("Tempo attivo · mediana", "Active time · median"),
    "WALL_MEDIAN": ("Durata richiesta · mediana", "Request duration · median"),
    "MEDIAN": ("Mediana", "Median"),
    "P95": ("95° percentile", "95th percentile"),
    "SECONDS": ("s", "s"),
    "TPS": ("t/s", "t/s"),
    "TOKEN_UNIT": ("token", "tokens"),
    "DATA_QUALITY": ("Qualità delle misure", "Measurement quality"),
    "INCOMPLETE": ("Richieste incomplete", "Incomplete requests"),
    "DROPPED_EVENTS": ("Eventi persi", "Lost events"),
    "UNATTRIBUTED_CALLS": ("Chiamate non attribuite", "Unattributed calls"),
    "PREFILL": ("Prefill", "Prefill"),
    "GENERATION": ("Generazione", "Generation"),
    "PARTIAL_HELP": ("≥ indica un totale parziale. Il trattino indica una misura sconosciuta; nessun valore mancante viene sostituito con zero. I riepiloghi coprono l'intero periodo filtrato.", "≥ marks a partial total. A dash marks an unknown measurement; missing values are never replaced with zero. Summaries cover the whole filtered period."),
    "READ_TRUNCATED": ("Statistiche parziali: raggiunto il limite di {limit} richieste o chiamate. Riduci il periodo o aggiungi filtri per leggere tutti i dati.", "Partial statistics: the limit of {limit} requests or calls was reached. Reduce the period or add filters to read all data."),
    "COLLECTOR_UNAVAILABLE": ("Stato del raccoglitore non disponibile. L'ultima acquisizione può riferirsi a dati storici.", "Collector status is unavailable. The last acquisition may refer to historical data."),
    "COLLECTION_HEALTH": ("Salute della raccolta", "Collection health"),
    "COLLECTOR_DROPPED_EVENTS": ("Perdite del raccoglitore (cumulative)", "Collector losses (cumulative)"),
    "COLLECTOR_WRITE_ERRORS": ("Errori di scrittura (cumulativi)", "Write errors (cumulative)"),
    "COLLECTOR_COUNTERS_HELP": ("Contatori cumulativi dei raccoglitori, indipendenti dai filtri. Eventi persi o errori di scrittura indicano che le statistiche possono essere incomplete.", "Cumulative collector counters, independent of filters. Lost events or write errors indicate that statistics may be incomplete."),
    "TIMELINE_SPAN": ("Ampiezza degli intervalli osservati", "Observed interval span"),
    "OBSERVED_INTERVAL": ("Intervallo osservato", "Observed interval"),
    "TIMELINE_OMITTED": ("Chiamate senza intervallo visualizzato: {count}. Sono incluse nelle altre misure quando disponibili.", "Calls without a displayed interval: {count}. They are included in other measurements when available."),
    "UNAVAILABLE": ("—", "—"),
    "UNKNOWN": ("Sconosciuto", "Unknown"),
    "TOKENS_MISSING": ("Token non comunicati per le chiamate osservate", "Tokens not reported for the observed calls"),
    "PARTIAL_TOTAL": ("Totale parziale: alcune chiamate non hanno una misura", "Partial total: some calls have no measurement"),
    "STATUS_COMPLETED": ("Conclusa", "Completed"),
    "STATUS_IN_PROGRESS": ("In corso", "In progress"),
    "STATUS_AWAITING_INPUT": ("In attesa di risposta", "Awaiting input"),
    "STATUS_INTERRUPTED": ("Interrotta", "Interrupted"),
    "STATUS_EXPIRED": ("Scaduta", "Expired"),
    "STATUS_ERROR": ("Errore", "Error"),
    "STATUS_CANCELLED": ("Annullata", "Cancelled"),
    "STATUS_UNKNOWN": ("Stato sconosciuto", "Unknown status"),
    "UNKNOWN_MODEL": ("Modello sconosciuto", "Unknown model"),
    "UNKNOWN_PROVIDER": ("Fornitore sconosciuto", "Unknown provider"),
    "CONFIGURED": ("configurato, non attestato", "configured, not attested"),
    "REQUESTED_MODEL": ("Modello richiesto", "Requested model"),
    "MODEL_IDENTITY": ("Nome logico → modello fisico · fornitore", "Logical name → physical model · provider"),
    "MODEL_TABLE": ("Misure per nome logico e modello fisico", "Measurements by logical name and physical model"),
    "INPUT_OUTPUT": ("Token in / out", "Tokens in / out"),
    "PREFILL_TPS": ("Prefill · t/s", "Prefill · t/s"),
    "GENERATION_TPS": ("Generazione · t/s", "Generation · t/s"),
    "CALL_OUTPUT_TPS": ("Velocità chiamata · t/s", "Call speed · t/s"),
    "CALL_OUTPUT_SPEED": ("Velocità chiamata", "Call speed"),
    "CALL_MEDIAN_SECONDS": ("Tempo chiamata · mediana · s", "Call time · median · s"),
    "CALL_P95_SECONDS": ("Tempo chiamata · 95° percentile · s", "Call time · 95th percentile · s"),
    "CALL_LATENCY": ("Durata delle chiamate", "Call duration"),
    "COVERAGE": ("Copertura", "Coverage"),
    "COMPLETE_MEASURES": ("Misure complete", "Complete measurements"),
    "EVENT_UNIT": ("eventi", "events"),
    "PERCENT_UNIT": ("%", "%"),
    "REQUEST_COVERAGE_HELP": ("Copertura: richieste concluse con catena, chiamate, token e tempi completi. Gli eventi persi si contano una volta per richiesta, anche se usa più modelli.", "Coverage: completed requests with complete chains, calls, tokens, and timings. Lost events are counted once per request, including requests using several models."),
    "CALL_COVERAGE_HELP": ("Copertura: chiamate con token ingresso, token uscita e durata completa noti. Le fasi non comunicate dal fornitore restano non disponibili. Gli eventi persi si contano per richiesta.", "Coverage: calls with known input tokens, output tokens, and full duration. Phases not reported by the provider remain unavailable. Lost events are counted per request."),
    "MORE_METRICS": ("Altre misure", "More measurements"),
    "NO_MODELS": ("Nessuna chiamata ai modelli nel periodo filtrato.", "No model calls in the filtered period."),
    "MODEL_TOKEN_HELP": ("Modelli con tokenizzatori diversi restano distinti: il numero di token è un conteggio operativo e non confronta il volume semantico.", "Models with different tokenizers remain separate: token counts are operational measures and do not compare semantic volume."),
    "REQUEST_TABLE": ("Richieste nel periodo filtrato", "Requests in the filtered period"),
    "REQUEST": ("Richiesta", "Request"),
    "ACTIVE_SECONDS": ("Tempo attivo · s", "Active time · s"),
    "WALL_SECONDS": ("Durata totale richiesta · s", "Total request duration · s"),
    "TOTAL_TIME": ("Durata totale richiesta", "Total request duration"),
    "REQUEST_OUTPUT_TPS": ("Token generati / durata richiesta · t/s", "Generated tokens / request duration · t/s"),
    "REQUEST_OUTPUT_SPEED": ("Token generati / durata richiesta", "Generated tokens / request duration"),
    "NO_REQUESTS": ("Nessuna richiesta nel periodo filtrato.", "No requests in the filtered period."),
    "TABLE_PAGE_HELP": ("La tabella è paginata; riepiloghi e grafici usano tutte le misure filtrate.", "The table is paginated; summaries and charts use all filtered measurements."),
    "NEXT_PAGE": ("Pagina successiva", "Next page"),
    "STARTED_AT": ("Inizio · UTC", "Start · UTC"),
    "USER_WAIT_SECONDS": ("Attesa utente · s", "User wait · s"),
    "OBSERVED_TIMELINE": ("Intervalli osservati delle chiamate", "Observed call intervals"),
    "TIMELINE_HELP": ("Ogni barra rappresenta una chiamata sull'asse comune della richiesta; eventuali sovrapposizioni restano visibili. Le fasi senza posizione osservata sono riportate solo come durata.", "Each bar represents a call on the common request axis; overlaps remain visible. Phases without an observed position are shown only as durations."),
    "NO_TIMELINE": ("Non sono disponibili intervalli osservati da collocare sull'asse temporale. Le durate note restano nella tabella.", "No observed intervals are available to place on the timeline. Known durations remain in the table."),
    "LINKED_TURNS": ("Turni collegati", "Linked turns"),
    "TURN": ("Turno", "Turn"),
    "NO_TURNS": ("Nessun turno collegato disponibile.", "No linked turns available."),
    "CALL_TABLE": ("Singole chiamate ai modelli", "Individual model calls"),
    "CALL": ("Chiamata", "Call"),
    "ROLE_ATTEMPT": ("Attività / tentativo", "Workload / attempt"),
    "CACHE_TOKENS": ("Token ingresso in cache", "Cached input tokens"),
    "CALL_SECONDS": ("Tempo chiamata · s", "Call time · s"),
    "PREFILL_SECONDS_TPS": ("Prefill · s / t/s", "Prefill · s / t/s"),
    "GENERATION_SECONDS_TPS": ("Generazione · s / t/s", "Generation · s / t/s"),
    "PROVENANCE": ("Provenienza / lacune", "Sources / gaps"),
    "PARENT_CALL": ("Chiamata precedente", "Parent call"),
    "BINDING_REVISION": ("Associazione acquisita", "Recorded binding"),
    "ATTEMPT": ("Tentativo", "Attempt"),
    "REASONING_TOKENS": ("Token ragionamento attestati", "Attested reasoning tokens"),
    "PREFILL_TOKENS": ("Token processati nel prefill", "Tokens processed during prefill"),
    "GENERATION_TOKENS": ("Token di generazione", "Generation tokens"),
    "SOURCES_AND_GAPS": ("Fonti e misure mancanti", "Sources and missing measurements"),
    "SOURCE_PROVIDER": ("Comunicata dal fornitore", "Reported by the provider"),
    "SOURCE_OBSERVER": ("Misurata dal runtime", "Measured by the runtime"),
    "MISSING": ("Misura assente", "Missing measurement"),
    "INVALID_NUMBER": ("Valore numerico non valido", "Invalid numeric value"),
    "NOT_REPORTED": ("Non comunicata dal fornitore", "Not reported by the provider"),
    "TRANSPORT_ERROR": ("Errore di trasporto", "Transport error"),
    "UNSUPPORTED_PROVIDER": ("Fornitore non supportato per questa misura", "Provider not supported for this measurement"),
    "INCOMPLETE_CACHE": ("Contatori della cache incompleti", "Incomplete cache counters"),
    "NO_CALLS": ("Nessuna chiamata osservata per questa richiesta.", "No calls observed for this request."),
    "PHASE_POSITION_HELP": ("I tempi delle fasi vengono dal motore quando disponibili. La posizione delle fasi non viene dedotta dalla durata né dal tempo al primo token.", "Phase durations come from the engine when available. Phase positions are not inferred from duration or time to the first token."),
    "EXPORT": ("Esporta misure", "Export measurements"),
    "PAUSE": ("Pausa aggiornamenti", "Pause updates"),
    "RESUME": ("Riprendi aggiornamenti", "Resume updates"),
    "BACK_REQUESTS": ("← Elenco richieste", "← Request list"),
    "LAST_ACQUISITION": ("Ultima acquisizione", "Last acquisition"),
    "REFRESH_HELP": ("Aggiornamento ogni 5 secondi mentre la pagina è visibile.", "Updates every 5 seconds while the page is visible."),
    "CHARTS": ("Andamento delle misure", "Measurement trends"),
    "SERIES_HELP": ("Le serie distinguono nome logico, modello fisico e fornitore acquisiti alla chiamata. Seleziona fino a 12 coppie; le lacune restano vuote. Il tempo complessivo appartiene alla richiesta, anche quando usa più modelli.", "Series distinguish the logical name, physical model and provider recorded for each call. Select up to 12 pairs; gaps remain empty. Total time belongs to the request, including requests using multiple models."),
    "MODEL_SERIES": ("Serie dei modelli visibili", "Visible model series"),
    "CHARTS_REQUIRE_JS": ("Per i grafici e l'aggiornamento automatico occorre JavaScript. Le tabelle sono disponibili in Richieste e Prestazioni modelli.", "Charts and automatic updates require JavaScript. Tables are available in Requests and Model performance."),
    "FORMULAS": ("Come sono calcolate le misure", "How measurements are calculated"),
    "PREFILL_FORMULA": ("Token effettivamente processati nel prefill ÷ durata prefill in secondi. Per aggregare si sommano i token e le durate delle sole chiamate con entrambe le misure valide.", "Tokens actually processed during prefill ÷ prefill duration in seconds. Aggregation sums tokens and durations only from calls with both measurements valid."),
    "GENERATION_FORMULA": ("Token di generazione attestati ÷ durata generazione in secondi. L'aggregato è il rapporto fra le somme, senza mediare le velocità delle chiamate.", "Attested generation tokens ÷ generation duration in seconds. The aggregate is a ratio of sums, without averaging call speeds."),
    "REQUEST_FORMULA": ("Token uscita di tutte le chiamate della richiesta ÷ tempo complessivo in secondi. Comprende attese, tentativi e riprese; resta sconosciuta se la catena o i token sono incompleti.", "Output tokens from all calls in the request ÷ total time in seconds. Includes waits, attempts and continuations; remains unknown if the chain or token counts are incomplete."),
    "CALL_FORMULA": ("Token uscita ÷ durata completa della chiamata in secondi: prefill + generazione, compresi coda e trasporto. L'aggregato somma token e durate delle sole chiamate valide (media ponderata per la durata).", "Output tokens ÷ full call duration in seconds: prefill + generation, including queueing and transport. Aggregation sums tokens and durations of valid calls only (duration-weighted mean)."),
    "ACTIVE_FORMULA": ("Somma delle durate osservate dei segmenti di elaborazione della richiesta, misurate con orologio monotono. Esclude le attese dell'utente; il tempo complessivo resta una misura distinta.", "Sum of observed request processing segment durations, measured with a monotonic clock. Excludes user waits; total time remains a separate measurement."),
    "STALE": ("Dati obsoleti: verificare l'acquisizione", "Stale data: check acquisition"),
    "READ_ERROR": ("Il Monitor non è raggiungibile. Le ultime misure restano visibili.", "Monitor is unavailable. The last measurements remain visible."),
    "NO_CHART_DATA": ("Nessuna misura valida per questo grafico.", "No valid measurements for this chart."),
    "SERIES_LIMIT": ("Massimo 12 coppie visibili: deseleziona una coppia prima di aggiungerne un'altra.", "At most 12 visible pairs: deselect a pair before adding another."),
    "SAMPLES": ("Campioni validi / totali", "Valid / total samples"),
}


def sync(path: Path) -> int:
    sys.path.insert(0, str(ROOT / "runtime"))
    import i18n
    import ui_surfaces

    i18n.DB_PATH = path
    i18n._SEED_DB_PATH = path
    i18n._conn = None
    conn = i18n._open()
    conn.execute(
        "CREATE TABLE IF NOT EXISTS i18n_seed_history ("
        "key TEXT NOT NULL, lang TEXT NOT NULL, version_hash TEXT NOT NULL, "
        "PRIMARY KEY (key, lang, version_hash))"
    )
    catalog = {f"UI_MONITOR_{suffix}": {"it": it, "en": en}
               for suffix, (it, en) in TRANSLATIONS.items()}
    for lang in ("it", "en"):
        for key, text in ui_surfaces.localization_inventory(lang):
            if key == "UI_SECTION_MONITOR_LABEL" or key == "UI_SURFACE_EXECUTOR_STATS_LABEL" or key.startswith("UI_SURFACE_MONITOR_"):
                catalog.setdefault(key, {})[lang] = text
    for key, translations in sorted(catalog.items()):
        for lang, previous in conn.execute(
            "SELECT lang, text FROM i18n WHERE key=? AND text IS NOT NULL", (key,),
        ).fetchall():
            conn.execute(
                "INSERT OR IGNORE INTO i18n_seed_history (key,lang,version_hash) "
                "VALUES (?,?,?)", (key, lang, i18n._sha256_full(previous)),
            )
        i18n.set_catalog_translations(key, translations, source_lang="it")
    conn.commit()
    i18n._checkpoint(conn)
    conn.close()
    i18n._conn = None
    return len(catalog) * 2


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=ROOT / "install/data/i18n_seed.sqlite")
    args = parser.parse_args()
    count = sync(args.db)
    print(f"Monitor: {count} traduzioni nel seed {args.db}")


if __name__ == "__main__":
    main()
